const x = {
    "001": "Heart transplant or implant of heart assist system with MCC",
    "002": "Heart transplant or implant of heart assist system without MCC",
    "003": "ECMO or tracheostomy with MV >96 hours or PDX except face, mouth and neck with major O.R. procedure",
    "004": "Tracheostomy with MV >96 hours or PDX except face, mouth and neck without major O.R. procedure",
    "005": "Liver transplant with MCC or intestinal transplant",
    "006": "Liver transplant without MCC",
    "007": "Lung transplant",
    "008": "Simultaneous pancreas and kidney transplant",
    "010": "Pancreas transplant",
    "011": "Tracheostomy for face, mouth & neck diagnoses or laryngectomy with MCC",
    "012": "Tracheostomy for face, mouth & neck diagnoses or laryngectomy with CC",
    "013": "Tracheostomy for face, mouth & neck diagnoses or laryngectomy without CC/MCC",
    "014": "Allogeneic bone marrow transplant",
    "016": "Autologous bone marrow transplant with CC/MCC or T-cell immunotherapy",
    "017": "Autologous bone marrow transplant without CC/MCC",
    "020": "Intracranial vascular procedures with PDX hemorrhage with MCC",
    "021": "Intracranial vascular procedures with PDX hemorrhage with CC",
    "022": "Intracranial vascular procedures with PDX hemorrhage without CC/MCC",
    "023": "Craniotomy with major device implant or acute complex CNS PDX with MCC or chemotherapy implant or epilepsy with neurostimulator",
    "024": "Craniotomy with major device implant or acute complex CNS PDX without MCC",
    "025": "Craniotomy and endovascular intracranial procedures with MCC",
    "026": "Craniotomy and endovascular intracranial procedures with CC",
    "027": "Craniotomy and endovascular intracranial procedures without CC/MCC",
    "028": "Spinal procedures with MCC",
    "029": "Spinal procedures with CC or spinal neurostimulators",
    "030": "Spinal procedures without CC/MCC",
    "031": "Ventricular shunt procedures with MCC",
    "032": "Ventricular shunt procedures with CC",
    "033": "Ventricular shunt procedures without CC/MCC",
    "034": "Carotid artery stent procedure with MCC",
    "035": "Carotid artery stent procedure with CC",
    "036": "Carotid artery stent procedure without CC/MCC",
    "037": "Extracranial procedures with MCC",
    "038": "Extracranial procedures with CC",
    "039": "Extracranial procedures without CC/MCC",
    "040": "Peripheral, cranial nerve and other nervous system procedures with MCC",
    "041": "Peripheral, cranial nerve and other nervous system procedures with CC or peripheral neurostimulator",
    "042": "Peripheral, cranial nerve and other nervous system procedures without CC/MCC",
    "052": "Spinal disorders and injuries with CC/MCC",
    "053": "Spinal disorders and injuries without CC/MCC",
    "054": "Nervous system neoplasms with MCC",
    "055": "Nervous system neoplasms without MCC",
    "056": "Degenerative nervous system disorders with MCC",
    "057": "Degenerative nervous system disorders without MCC",
    "058": "Multiple sclerosis and cerebellar ataxia with MCC",
    "059": "Multiple sclerosis and cerebellar ataxia with CC",
    "060": "Multiple sclerosis and cerebellar ataxia without CC/MCC",
    "061": "Ischemic stroke, precerebral occlusion or transient ischemia with thrombolytic agent with MCC",
    "062": "Ischemic stroke, precerebral occlusion or transient ischemia with thrombolytic agent with CC",
    "063": "Ischemic stroke, precerebral occlusion or transient ischemia with thrombolytic agent without CC/MCC",
    "064": "Intracranial hemorrhage or cerebral infarction with MCC",
    "065": "Intracranial hemorrhage or cerebral infarction with CC or tPA in 24 hours",
    "066": "Intracranial hemorrhage or cerebral infarction without CC/MCC",
    "067": "Nonspecific CVA and precerebral occlusion without infarction with MCC",
    "068": "Nonspecific CVA and precerebral occlusion without infarction without MCC",
    "069": "Transient ischemia without thrombolytic",
    "070": "Nonspecific cerebrovascular disorders with MCC",
    "071": "Nonspecific cerebrovascular disorders with CC",
    "072": "Nonspecific cerebrovascular disorders without CC/MCC",
    "073": "Cranial and peripheral nerve disorders with MCC",
    "074": "Cranial and peripheral nerve disorders without MCC",
    "075": "Viral meningitis with CC/MCC",
    "076": "Viral meningitis without CC/MCC",
    "077": "Hypertensive encephalopathy with MCC",
    "078": "Hypertensive encephalopathy with CC",
    "079": "Hypertensive encephalopathy without CC/MCC",
    "080": "Nontraumatic stupor and coma with MCC",
    "081": "Nontraumatic stupor and coma without MCC",
    "082": "Traumatic stupor and coma, coma >1 hour with MCC",
    "083": "Traumatic stupor and coma, coma >1 hour with CC",
    "084": "Traumatic stupor and coma, coma >1 hour without CC/MCC",
    "085": "Traumatic stupor and coma, coma <1 hour with MCC",
    "086": "Traumatic stupor and coma, coma <1 hour with CC",
    "087": "Traumatic stupor and coma, coma <1 hour without CC/MCC",
    "088": "Concussion with MCC",
    "089": "Concussion with CC",
    "090": "Concussion without CC/MCC",
    "091": "Other disorders of nervous system with MCC",
    "092": "Other disorders of nervous system with CC",
    "093": "Other disorders of nervous system without CC/MCC",
    "094": "Bacterial and tuberculous infections of nervous system with MCC",
    "095": "Bacterial and tuberculous infections of nervous system with CC",
    "096": "Bacterial and tuberculous infections of nervous system without CC/MCC",
    "097": "Non-bacterial infection of nervous system except viral meningitis with MCC",
    "098": "Non-bacterial infection of nervous system except viral meningitis with CC",
    "099": "Non-bacterial infection of nervous system except viral meningitis without CC/MCC",
    "100": "Seizures with MCC",
    "101": "Seizures without MCC",
    "102": "Headaches with MCC",
    "103": "Headaches without MCC",
    "113": "Orbital procedures with CC/MCC",
    "114": "Orbital procedures without CC/MCC",
    "115": "Extraocular procedures except orbit",
    "116": "Intraocular procedures with CC/MCC",
    "117": "Intraocular procedures without CC/MCC",
    "121": "Acute major eye infections with CC/MCC",
    "122": "Acute major eye infections without CC/MCC",
    "123": "Neurological eye disorders",
    "124": "Other disorders of the eye with MCC",
    "125": "Other disorders of the eye without MCC",
    "129": "Major head and neck procedures with CC/MCC or major device",
    "130": "Major head and neck procedures without CC/MCC",
    "131": "Cranial and facial procedures with CC/MCC",
    "132": "Cranial and facial procedures without CC/MCC",
    "133": "Other ear, nose, mouth and throat O.R. procedures with CC/MCC",
    "134": "Other ear, nose, mouth and throat O.R. procedures without CC/MCC",
    "135": "Sinus and mastoid procedures with CC/MCC",
    "136": "Sinus and mastoid procedures without CC/MCC",
    "137": "Mouth procedures with CC/MCC",
    "138": "Mouth procedures without CC/MCC",
    "139": "Salivary gland procedures",
    "146": "Ear, nose, mouth and throat malignancy with MCC",
    "147": "Ear, nose, mouth and throat malignancy with CC",
    "148": "Ear, nose, mouth and throat malignancy without CC/MCC",
    "149": "Dysequilibrium",
    "150": "Epistaxis with MCC",
    "151": "Epistaxis without MCC",
    "152": "Otitis media and URI with MCC",
    "153": "Otitis media and URI without MCC",
    "154": "Other ear, nose, mouth and throat diagnoses with MCC",
    "155": "Other ear, nose, mouth and throat diagnoses with CC",
    "156": "Other ear, nose, mouth and throat diagnoses without CC/MCC",
    "157": "Dental and oral diseases with MCC",
    "158": "Dental and oral diseases with CC",
    "159": "Dental and oral diseases without CC/MCC",
    "163": "Major chest procedures with MCC",
    "164": "Major chest procedures with CC",
    "165": "Major chest procedures without CC/MCC",
    "166": "Other respiratory system O.R. procedures with MCC",
    "167": "Other respiratory system O.R. procedures with CC",
    "168": "Other respiratory system O.R. procedures without CC/MCC",
    "175": "Pulmonary embolism with MCC or acute cor pulmonale",
    "176": "Pulmonary embolism without MCC",
    "177": "Respiratory infections and inflammations with MCC",
    "178": "Respiratory infections and inflammations with CC",
    "179": "Respiratory infections and inflammations without CC/MCC",
    "180": "Respiratory neoplasms with MCC",
    "181": "Respiratory neoplasms with CC",
    "182": "Respiratory neoplasms without CC/MCC",
    "183": "Major chest trauma with MCC",
    "184": "Major chest trauma with CC",
    "185": "Major chest trauma without CC/MCC",
    "186": "Pleural effusion with MCC",
    "187": "Pleural effusion with CC",
    "188": "Pleural effusion without CC/MCC",
    "189": "Pulmonary edema and respiratory failure",
    "190": "Chronic obstructive pulmonary disease with MCC",
    "191": "Chronic obstructive pulmonary disease with CC",
    "192": "Chronic obstructive pulmonary disease without CC/MCC",
    "193": "Simple pneumonia and pleurisy with MCC",
    "194": "Simple pneumonia and pleurisy with CC",
    "195": "Simple pneumonia and pleurisy without CC/MCC",
    "196": "Interstitial lung disease with MCC",
    "197": "Interstitial lung disease with CC",
    "198": "Interstitial lung disease without CC/MCC",
    "199": "Pneumothorax with MCC",
    "200": "Pneumothorax with CC",
    "201": "Pneumothorax without CC/MCC",
    "202": "Bronchitis and asthma with CC/MCC",
    "203": "Bronchitis and asthma without CC/MCC",
    "204": "Respiratory signs and symptoms",
    "205": "Other respiratory system diagnoses with MCC",
    "206": "Other respiratory system diagnoses without MCC",
    "207": "Respiratory system diagnosis with ventilator support >96 hours",
    "208": "Respiratory system diagnosis with ventilator support <=96 hours",
    "215": "Other heart assist system implant",
    "216": "Cardiac valve and other major cardiothoracic procedures with cardiac catheterization with MCC",
    "217": "Cardiac valve and other major cardiothoracic procedures with cardiac catheterization with CC",
    "218": "Cardiac valve and other major cardiothoracic procedures with cardiac catheterization without CC/MCC",
    "219": "Cardiac valve and other major cardiothoracic procedures without cardiac catheterization with MCC",
    "220": "Cardiac valve and other major cardiothoracic procedures without cardiac catheterization with CC",
    "221": "Cardiac valve and other major cardiothoracic procedures without cardiac catheterization without CC/MCC",
    "222": "Cardiac defibrillator implant with cardiac catheterization with AMI/HF/shock with MCC",
    "223": "Cardiac defibrillator implant with cardiac catheterization with AMI/HF/shock without MCC",
    "224": "Cardiac defibrillator implant with cardiac catheterization without AMI/HF/shock with MCC",
    "225": "Cardiac defibrillator implant with cardiac catheterization without AMI/HF/shock without MCC",
    "226": "Cardiac defibrillator implant without cardiac catheterization with MCC",
    "227": "Cardiac defibrillator implant without cardiac catheterization without MCC",
    "228": "Other cardiothoracic procedures with MCC",
    "229": "Other cardiothoracic procedures without MCC",
    "231": "Coronary bypass with PTCA with MCC",
    "232": "Coronary bypass with PTCA without MCC",
    "233": "Coronary bypass with cardiac catheterization with MCC",
    "234": "Coronary bypass with cardiac catheterization without MCC",
    "235": "Coronary bypass without cardiac catheterization with MCC",
    "236": "Coronary bypass without cardiac catheterization without MCC",
    "239": "Amputation for circulatory system disorders except upper limb and toe with MCC",
    "240": "Amputation for circulatory system disorders except upper limb and toe with CC",
    "241": "Amputation for circulatory system disorders except upper limb and toe without CC/MCC",
    "242": "Permanent cardiac pacemaker implant with MCC",
    "243": "Permanent cardiac pacemaker implant with CC",
    "244": "Permanent cardiac pacemaker implant without CC/MCC",
    "245": "AICD generator procedures",
    "246": "Percutaneous cardiovascular procedures with drug-eluting stent with MCC or 4+ arteries or stents",
    "247": "Percutaneous cardiovascular procedures with drug-eluting stent without MCC",
    "248": "Percutaneous cardiovascular procedures with non-drug-eluting stent with MCC or 4+ arteries or stents",
    "249": "Percutaneous cardiovascular procedures with non-drug-eluting stent without MCC",
    "250": "Percutaneous cardiovascular procedures without coronary artery stent with MCC",
    "251": "Percutaneous cardiovascular procedures without coronary artery stent without MCC",
    "252": "Other vascular procedures with MCC",
    "253": "Other vascular procedures with CC",
    "254": "Other vascular procedures without CC/MCC",
    "255": "Upper limb and toe amputation for circulatory system disorders with MCC",
    "256": "Upper limb and toe amputation for circulatory system disorders with CC",
    "257": "Upper limb and toe amputation for circulatory system disorders without CC/MCC",
    "258": "Cardiac pacemaker device replacement with MCC",
    "259": "Cardiac pacemaker device replacement without MCC",
    "260": "Cardiac pacemaker revision except device replacement with MCC",
    "261": "Cardiac pacemaker revision except device replacement with CC",
    "262": "Cardiac pacemaker revision except device replacement without CC/MCC",
    "263": "Vein ligation and stripping",
    "264": "Other circulatory system O.R. procedures",
    "265": "AICD lead procedures",
    "266": "Endovascular cardiac valve replacement and supplement procedures with MCC",
    "267": "Endovascular cardiac valve replacement and supplement procedures without MCC",
    "268": "Aortic and heart assist procedures except pulsation balloon with MCC",
    "269": "Aortic and heart assist procedures except pulsation balloon without MCC",
    "270": "Other major cardiovascular procedures with MCC",
    "271": "Other major cardiovascular procedures with CC",
    "272": "Other major cardiovascular procedures without CC/MCC",
    "273": "Percutaneous intracardiac procedures with MCC",
    "274": "Percutaneous intracardiac procedures without MCC",
    "280": "Acute myocardial infarction, discharged alive with MCC",
    "281": "Acute myocardial infarction, discharged alive with CC",
    "282": "Acute myocardial infarction, discharged alive without CC/MCC",
    "283": "Acute myocardial infarction, expired with MCC",
    "284": "Acute myocardial infarction, expired with CC",
    "285": "Acute myocardial infarction, expired without CC/MCC",
    "286": "Circulatory disorders except AMI, with cardiac cateterization with MCC",
    "287": "Circulatory disorders except AMI, with cardiac cateterization without MCC",
    "288": "Acute and subacute endocarditis with MCC",
    "289": "Acute and subacute endocarditis with CC",
    "290": "Acute and subacute endocarditis without CC/MCC",
    "291": "Heart failure and shock with MCC",
    "292": "Heart failure and shock with CC",
    "293": "Heart failure and shock without CC/MCC",
    "294": "Deep vein thrombophlebitis with CC/MCC",
    "295": "Deep vein thrombophlebitis without CC/MCC",
    "296": "Cardiac arrest, unexplained with MCC",
    "297": "Cardiac arrest, unexplained with CC",
    "298": "Cardiac arrest, unexplained without CC/MCC",
    "299": "Peripheral vascular disorders with MCC",
    "300": "Peripheral vascular disorders with CC",
    "301": "Peripheral vascular disorders without CC/MCC",
    "302": "Atherosclerosis with MCC",
    "303": "Atherosclerosis without MCC",
    "304": "Hypertension with MCC",
    "305": "Hypertension without MCC",
    "306": "Cardiac congenital and valvular disorders with MCC",
    "307": "Cardiac congenital and valvular disorders without MCC",
    "308": "Cardiac arrhythmia and conduction disorders with MCC",
    "309": "Cardiac arrhythmia and conduction disorders with CC",
    "310": "Cardiac arrhythmia and conduction disorders without CC/MCC",
    "311": "Angina pectoris",
    "312": "Syncope and collapse",
    "313": "Chest pain",
    "314": "Other circulatory system diagnoses with MCC",
    "315": "Other circulatory system diagnoses with CC",
    "316": "Other circulatory system diagnoses without CC/MCC",
    "319": "Other endovascular cardiac valve procedures with MCC",
    "320": "Other endovascular cardiac valve procedures without MCC",
    "326": "Stomach, esophageal and duodenal procedures with MCC",
    "327": "Stomach, esophageal and duodenal procedures with CC",
    "328": "Stomach, esophageal and duodenal procedures without CC/MCC",
    "329": "Major small and large bowel procedures with MCC",
    "330": "Major small and large bowel procedures with CC",
    "331": "Major small and large bowel procedures without CC/MCC",
    "332": "Rectal resection with MCC",
    "333": "Rectal resection with CC",
    "334": "Rectal resection without CC/MCC",
    "335": "Peritoneal adhesiolysis with MCC",
    "336": "Peritoneal adhesiolysis with CC",
    "337": "Peritoneal adhesiolysis without CC/MCC",
    "338": "Appendectomy with complicated principal diagnosis with MCC",
    "339": "Appendectomy with complicated principal diagnosis with CC",
    "340": "Appendectomy with complicated principal diagnosis without CC/MCC",
    "341": "Appendectomy without complicated principal diagnosis with MCC",
    "342": "Appendectomy without complicated principal diagnosis with CC",
    "343": "Appendectomy without complicated principal diagnosis without CC/MCC",
    "344": "Minor small and large bowel procedures with MCC",
    "345": "Minor small and large bowel procedures with CC",
    "346": "Minor small and large bowel procedures without CC/MCC",
    "347": "Anal and stomal procedures with MCC",
    "348": "Anal and stomal procedures with CC",
    "349": "Anal and stomal procedures without CC/MCC",
    "350": "Inguinal and femoral hernia procedures with MCC",
    "351": "Inguinal and femoral hernia procedures with CC",
    "352": "Inguinal and femoral hernia procedures without CC/MCC",
    "353": "Hernia procedures except inguinal and femoral with MCC",
    "354": "Hernia procedures except inguinal and femoral with CC",
    "355": "Hernia procedures except inguinal and femoral without CC/MCC",
    "356": "Other digestive system O.R. procedures with MCC",
    "357": "Other digestive system O.R. procedures with CC",
    "358": "Other digestive system O.R. procedures without CC/MCC",
    "368": "Major esophageal disorders with MCC",
    "369": "Major esophageal disorders with CC",
    "370": "Major esophageal disorders without CC/MCC",
    "371": "Major gastrointestinal disorders and peritoneal infections with MCC",
    "372": "Major gastrointestinal disorders and peritoneal infections with CC",
    "373": "Major gastrointestinal disorders and peritoneal infections without CC/MCC",
    "374": "Digestive malignancy with MCC",
    "375": "Digestive malignancy with CC",
    "376": "Digestive malignancy without CC/MCC",
    "377": "G.I. hemorrhage with MCC",
    "378": "G.I. hemorrhage with CC",
    "379": "G.I. hemorrhage without CC/MCC",
    "380": "Complicated peptic ulcer with MCC",
    "381": "Complicated peptic ulcer with CC",
    "382": "Complicated peptic ulcer without CC/MCC",
    "383": "Uncomplicated peptic ulcer with MCC",
    "384": "Uncomplicated peptic ulcer without MCC",
    "385": "Inflammatory bowel disease with MCC",
    "386": "Inflammatory bowel disease with CC",
    "387": "Inflammatory bowel disease without CC/MCC",
    "388": "G.I. obstruction with MCC",
    "389": "G.I. obstruction with CC",
    "390": "G.I. obstruction without CC/MCC",
    "391": "Esophagitis, gastroenteritis and miscellaneous digestive disorders with MCC",
    "392": "Esophagitis, gastroenteritis and miscellaneous digestive disorders without MCC",
    "393": "Other digestive system diagnoses with MCC",
    "394": "Other digestive system diagnoses with CC",
    "395": "Other digestive system diagnoses without CC/MCC",
    "405": "Pancreas, liver and shunt procedures with MCC",
    "406": "Pancreas, liver and shunt procedures with CC",
    "407": "Pancreas, liver and shunt procedures without CC/MCC",
    "408": "Biliary tract procedure except only cholecystectomy with or without C.D.E. with MCC",
    "409": "Biliary tract procedure except only cholecystectomy with or without C.D.E. with CC",
    "410": "Biliary tract procedure except only cholecystectomy with or without C.D.E. without CC/MCC",
    "411": "Cholecystectomy with C.D.E. with MCC",
    "412": "Cholecystectomy with C.D.E. with CC",
    "413": "Cholecystectomy with C.D.E. without CC/MCC",
    "414": "Cholecystectomy except by laparoscope without C.D.E. with MCC",
    "415": "Cholecystectomy except by laparoscope without C.D.E. with CC",
    "416": "Cholecystectomy except by laparoscope without C.D.E. without CC/MCC",
    "417": "Laparoscopic cholecystectomy without C.D.E. with MCC",
    "418": "Laparoscopic cholecystectomy without C.D.E. with CC",
    "419": "Laparoscopic cholecystectomy without C.D.E. without CC/MCC",
    "420": "Hepatobiliary diagnostic procedures with MCC",
    "421": "Hepatobiliary diagnostic procedures with CC",
    "422": "Hepatobiliary diagnostic procedures without CC/MCC",
    "423": "Other hepatobiliary or pancreas O.R. procedures with MCC",
    "424": "Other hepatobiliary or pancreas O.R. procedures with CC",
    "425": "Other hepatobiliary or pancreas O.R. procedures without CC/MCC",
    "432": "Cirrhosis and alcoholic hepatitis with MCC",
    "433": "Cirrhosis and alcoholic hepatitis with CC",
    "434": "Cirrhosis and alcoholic hepatitis without CC/MCC",
    "435": "Malignancy of hepatobiliary system or pancreas with MCC",
    "436": "Malignancy of hepatobiliary system or pancreas with CC",
    "437": "Malignancy of hepatobiliary system or pancreas without CC/MCC",
    "438": "Disorders of pancreas except malignancy with MCC",
    "439": "Disorders of pancreas except malignancy with CC",
    "440": "Disorders of pancreas except malignancy without CC/MCC",
    "441": "Disorders of liver except malignancy, cirrhosis or alcoholic hepatitis with MCC",
    "442": "Disorders of liver except malignancy, cirrhosis or alcoholic hepatitis with CC",
    "443": "Disorders of liver except malignancy, cirrhosis or alcoholic hepatitis without CC/MCC",
    "444": "Disorders of the biliary tract with MCC",
    "445": "Disorders of the biliary tract with CC",
    "446": "Disorders of the biliary tract without CC/MCC",
    "453": "Combined anterior/posterior spinal fusion with MCC",
    "454": "Combined anterior/posterior spinal fusion with CC",
    "455": "Combined anterior/posterior spinal fusion without CC/MCC",
    "456": "Spinal fusion except cervical with spinal curvature or malignancy or infection or extensive fusions with MCC",
    "457": "Spinal fusion except cervical with spinal curvature or malignancy or infection or extensive fusions with CC",
    "458": "Spinal fusion except cervical with spinal curvature or malignancy or infection or extensive fusions without CC/MCC",
    "459": "Spinal fusion except cervical with MCC",
    "460": "Spinal fusion except cervical without MCC",
    "461": "Bilateral or multiple major joint procedures of lower extremity with MCC",
    "462": "Bilateral or multiple major joint procedures of lower extremity without MCC",
    "463": "Wound debridement and skin graft except hand for musculoskeletal system and connective tissue disorders with MCC",
    "464": "Wound debridement and skin graft except hand for musculoskeletal system and connective tissue disorders with CC",
    "465": "Wound debridement and skin graft except hand for musculoskeletal system and connective tissue disorders without CC/MCC",
    "466": "Revision of hip or knee replacement with MCC",
    "467": "Revision of hip or knee replacement with CC",
    "468": "Revision of hip or knee replacement without CC/MCC",
    "469": "Major hip and knee joint replacement or reattachment of lower extremity with MCC or total ankle replacement",
    "470": "Major hip and knee joint replacement or reattachment of lower extremity without MCC",
    "471": "Cervical spinal fusion with MCC",
    "472": "Cervical spinal fusion with CC",
    "473": "Cervical spinal fusion without CC/MCC",
    "474": "Amputation for musculoskeletal system and connective tissue disorders with MCC",
    "475": "Amputation for musculoskeletal system and connective tissue disorders with CC",
    "476": "Amputation for musculoskeletal system and connective tissue disorders without CC/MCC",
    "477": "Biopsies of musculoskeletal system and connective tissue with MCC",
    "478": "Biopsies of musculoskeletal system and connective tissue with CC",
    "479": "Biopsies of musculoskeletal system and connective tissue without CC/MCC",
    "480": "Hip and femur procedures except major joint with MCC",
    "481": "Hip and femur procedures except major joint with CC",
    "482": "Hip and femur procedures except major joint without CC/MCC",
    "483": "Major joint/limb reattachment procedure of upper extremities",
    "485": "Knee procedures with PDX of infection with MCC",
    "486": "Knee procedures with PDX of infection with CC",
    "487": "Knee procedures with PDX of infection without CC/MCC",
    "488": "Knee procedures without PDX of infection with CC/MCC",
    "489": "Knee procedures without PDX of infection without CC/MCC",
    "492": "Lower extremity and humerus procedures except hip, foot and femur with MCC",
    "493": "Lower extremity and humerus procedures except hip, foot and femur with CC",
    "494": "Lower extremity and humerus procedures except hip, foot and femur without CC/MCC",
    "495": "Local excision and removal of internal fixation devices except hip and femur with MCC",
    "496": "Local excision and removal of internal fixation devices except hip and femur with CC",
    "497": "Local excision and removal internal fixation devices except hip and femur without CC/MCC",
    "498": "Local excision and removal internal fixation devices of hip and femur with CC/MCC",
    "499": "Local excision and removal internal fixation devices of hip and femur without CC/MCC",
    "500": "Soft tissue procedures with MCC",
    "501": "Soft tissue procedures with CC",
    "502": "Soft tissue procedures without CC/MCC",
    "503": "Foot procedures with MCC",
    "504": "Foot procedures with CC",
    "505": "Foot procedures without CC/MCC",
    "506": "Major thumb or joint procedures",
    "507": "Major shoulder or elbow joint procedures with CC/MCC",
    "508": "Major shoulder or elbow joint procedures without CC/MCC",
    "509": "Arthroscopy",
    "510": "Shoulder, elbow or forearm procedures, except major joint procedures with MCC",
    "511": "Shoulder, elbow or forearm procedures, except major joint procedures with CC",
    "512": "Shoulder, elbow or forearm procedures, except major joint procedures without CC/MCC",
    "513": "Hand or wrist procedures, except major thumb or joint procedures with CC/MCC",
    "514": "Hand or wrist procedures, except major thumb or joint procedures without CC/MCC",
    "515": "Other musculoskeletal system and connective tissue O.R. procedures with MCC",
    "516": "Other musculoskeletal system and connective tissue O.R. procedures with CC",
    "517": "Other musculoskeletal system and connective tissue O.R. procedures without CC/MCC",
    "518": "Back and neck procedures except spinal fusion with MCC or disc device or neurostimulator",
    "519": "Back and neck procedures except spinal fusion with CC",
    "520": "Back and neck procedures except spinal fusion without CC/MCC",
    "533": "Fractures of femur with MCC",
    "534": "Fractures of femur without MCC",
    "535": "Fractures of hip and pelvis with MCC",
    "536": "Fractures of hip and pelvis without MCC",
    "537": "Sprains, strains, and dislocations of hip, pelvis and thigh with CC/MCC",
    "538": "Sprains, strains, and dislocations of hip, pelvis and thigh without CC/MCC",
    "539": "Osteomyelitis with MCC",
    "540": "Osteomyelitis with CC",
    "541": "Osteomyelitis without CC/MCC",
    "542": "Pathological fractures and musculoskeletal and connective tissue malignancy with MCC",
    "543": "Pathological fractures and musculoskeletal and connective tissue malignancy with CC",
    "544": "Pathological fractures and musculoskeletal and connective tissue malignancy without CC/MCC",
    "545": "Connective tissue disorders with MCC",
    "546": "Connective tissue disorders with CC",
    "547": "Connective tissue disorders without CC/MCC",
    "548": "Septic arthritis with MCC",
    "549": "Septic arthritis with CC",
    "550": "Septic arthritis without CC/MCC",
    "551": "Medical back problems with MCC",
    "552": "Medical back problems without MCC",
    "553": "Bone diseases and arthropathies with MCC",
    "554": "Bone diseases and arthropathies without MCC",
    "555": "Signs and symptoms of musculoskeletal system and connective tissue with MCC",
    "556": "Signs and symptoms of musculoskeletal system and connective tissue without MCC",
    "557": "Tendonitis, myositis and bursitis with MCC",
    "558": "Tendonitis, myositis and bursitis without MCC",
    "559": "Aftercare, musculoskeletal system and connective tissue with MCC",
    "560": "Aftercare, musculoskeletal system and connective tissue with CC",
    "561": "Aftercare, musculoskeletal system and connective tissue without CC/MCC",
    "562": "Fracture, sprain, strain and dislocation except femur, hip, pelvis and thigh with MCC",
    "563": "Fracture, sprain, strain and dislocation except femur, hip, pelvis and thigh without MCC",
    "564": "Other musculoskeletal system and connective tissue diagnoses with MCC",
    "565": "Other musculoskeletal system and connective tissue diagnoses with CC",
    "566": "Other musculoskeletal system and connective tissue diagnoses without CC/MCC",
    "570": "Skin debridement with MCC",
    "571": "Skin debridement with CC",
    "572": "Skin debridement without CC/MCC",
    "573": "Skin graft for skin ulcer or cellulitis with MCC",
    "574": "Skin graft for skin ulcer or cellulitis with CC",
    "575": "Skin graft for skin ulcer or cellulitis without CC/MCC",
    "576": "Skin graft except for skin ulcer or cellulitis with MCC",
    "577": "Skin graft except for skin ulcer or cellulitis with CC",
    "578": "Skin graft except for skin ulcer or cellulitis without CC/MCC",
    "579": "Other skin, subcutaneous tissue and breast procedures with MCC",
    "580": "Other skin, subcutaneous tissue and breast procedures with CC",
    "581": "Other skin, subcutaneous tissue and breast procedures without CC/MCC",
    "582": "Mastectomy for malignancy with CC/MCC",
    "583": "Mastectomy for malignancy without CC/MCC",
    "584": "Breast biopsy, local excision and other breast procedures with CC/MCC",
    "585": "Breast biopsy, local excision and other breast procedures without CC/MCC",
    "592": "Skin ulcers with MCC",
    "593": "Skin ulcers with CC",
    "594": "Skin ulcers without CC/MCC",
    "595": "Major skin disorders with MCC",
    "596": "Major skin disorders without MCC",
    "597": "Malignant breast disorders with MCC",
    "598": "Malignant breast disorders with CC",
    "599": "Malignant breast disorders without CC/MCC",
    "600": "Non-malignant breast disorders with CC/MCC",
    "601": "Non-malignant breast disorders without CC/MCC",
    "602": "Cellulitis with MCC",
    "603": "Cellulitis without MCC",
    "604": "Trauma to the skin, subcutaneous tissue and breast with MCC",
    "605": "Trauma to the skin, subcutaneous tissue and breast without MCC",
    "606": "Minor skin disorders with MCC",
    "607": "Minor skin disorders without MCC",
    "614": "Adrenal and pituitary procedures with CC/MCC",
    "615": "Adrenal and pituitary procedures without CC/MCC",
    "616": "Amputation of lower limb for endocrine, nutritional and metabolic disorders with MCC",
    "617": "Amputation of lower limb for endocrine, nutritional and metabolic disorders with CC",
    "618": "Amputation of lower limb for endocrine, nutritional and metabolic disorders without CC/MCC",
    "619": "O.R. procedures for obesity with MCC",
    "620": "O.R. procedures for obesity with CC",
    "621": "O.R. procedures for obesity without CC/MCC",
    "622": "Skin grafts and wound debridement for endocrine, nutritional and metabolic disorders with MCC",
    "623": "Skin grafts and wound debridement for endocrine, nutritional and metabolic disorders with CC",
    "624": "Skin grafts and wound debridement for endocrine, nutritional and metabolic disorders without CC/MCC",
    "625": "Thyroid, parathyroid and thyroglossal procedures with MCC",
    "626": "Thyroid, parathyroid and thyroglossal procedures with CC",
    "627": "Thyroid, parathyroid and thyroglossal procedures without CC/MCC",
    "628": "Other endocrine, nutritional and metabolic O.R. procedures with MCC",
    "629": "Other endocrine, nutritional and metabolic O.R. procedures with CC",
    "630": "Other endocrine, nutritional and metabolic O.R. procedures without CC/MCC",
    "637": "Diabetes with MCC",
    "638": "Diabetes with CC",
    "639": "Diabetes without CC/MCC",
    "640": "Miscellaneous disorders of nutrition, metabolism, fluids and electrolytes with MCC",
    "641": "Miscellaneous disorders of nutrition, metabolism, fluids and electrolytes without MCC",
    "642": "Inborn and other disorders of metabolism",
    "643": "Endocrine disorders with MCC",
    "644": "Endocrine disorders with CC",
    "645": "Endocrine disorders without CC/MCC",
    "652": "Kidney transplant",
    "653": "Major bladder procedures with MCC",
    "654": "Major bladder procedures with CC",
    "655": "Major bladder procedures without CC/MCC",
    "656": "Kidney and ureter procedures for neoplasm with MCC",
    "657": "Kidney and ureter procedures for neoplasm with CC",
    "658": "Kidney and ureter procedures for neoplasm without CC/MCC",
    "659": "Kidney and ureter procedures for non-neoplasm with MCC",
    "660": "Kidney and ureter procedures for non-neoplasm with CC",
    "661": "Kidney and ureter procedures for non-neoplasm without CC/MCC",
    "662": "Minor bladder procedures with MCC",
    "663": "Minor bladder procedures with CC",
    "664": "Minor bladder procedures without CC/MCC",
    "665": "Prostatectomy with MCC",
    "666": "Prostatectomy with CC",
    "667": "Prostatectomy without CC/MCC",
    "668": "Transurethral procedures with MCC",
    "669": "Transurethral procedures with CC",
    "670": "Transurethral procedures without CC/MCC",
    "671": "Urethral procedures with CC/MCC",
    "672": "Urethral procedures without CC/MCC",
    "673": "Other kidney and urinary tract procedures with MCC",
    "674": "Other kidney and urinary tract procedures with CC",
    "675": "Other kidney and urinary tract procedures without CC/MCC",
    "682": "Renal failure with MCC",
    "683": "Renal failure with CC",
    "684": "Renal failure without CC/MCC",
    "686": "Kidney and urinary tract neoplasms with MCC",
    "687": "Kidney and urinary tract neoplasms with CC",
    "688": "Kidney and urinary tract neoplasms without CC/MCC",
    "689": "Kidney and urinary tract infections with MCC",
    "690": "Kidney and urinary tract infections without MCC",
    "693": "Urinary stones with MCC",
    "694": "Urinary stones without MCC",
    "695": "Kidney and urinary tract signs and symptoms with MCC",
    "696": "Kidney and urinary tract signs and symptoms without MCC",
    "697": "Urethral stricture",
    "698": "Other kidney and urinary tract diagnoses with MCC",
    "699": "Other kidney and urinary tract diagnoses with CC",
    "700": "Other kidney and urinary tract diagnoses without CC/MCC",
    "707": "Major male pelvic procedures with CC/MCC",
    "708": "Major male pelvic procedures without CC/MCC",
    "709": "Penis procedures with CC/MCC",
    "710": "Penis procedures without CC/MCC",
    "711": "Testes procedures with CC/MCC",
    "712": "Testes procedures without CC/MCC",
    "713": "Transurethral prostatectomy with CC/MCC",
    "714": "Transurethral prostatectomy without CC/MCC",
    "715": "Other male reproductive system O.R. procedures for malignancy with CC/MCC",
    "716": "Other male reproductive system O.R. procedures for malignancy without CC/MCC",
    "717": "Other male reproductive system O.R. procedures except malignancy with CC/MCC",
    "718": "Other male reproductive system O.R. proc except malignancy without CC/MCC",
    "722": "Malignancy, male reproductive system with MCC",
    "723": "Malignancy, male reproductive system with CC",
    "724": "Malignancy, male reproductive system without CC/MCC",
    "725": "Benign prostatic hypertrophy with MCC",
    "726": "Benign prostatic hypertrophy without MCC",
    "727": "Inflammation of the male reproductive system with MCC",
    "728": "Inflammation of the male reproductive system without MCC",
    "729": "Other male reproductive system diagnoses with CC/MCC",
    "730": "Other male reproductive system diagnoses without CC/MCC",
    "734": "Pelvic evisceration, radical hysterectomy and radical vulvectomy with CC/MCC",
    "735": "Pelvic evisceration, radical hysterectomy and radical vulvectomy without CC/MCC",
    "736": "Uterine and adnexa procedures for ovarian or adnexal malignancy with MCC",
    "737": "Uterine and adnexa procedures for ovarian or adnexal malignancy with CC",
    "738": "Uterine and adnexa procedures for ovarian or adnexal malignancy without CC/MCC",
    "739": "Uterine, adnexa procedures for non-ovarian and non-adnexal malignancy with MCC",
    "740": "Uterine, adnexa procedures for non-ovarian and non-adnexal malignancy with CC",
    "741": "Uterine, adnexa procedures for non-ovarian and non-adnexal malignancy without CC/MCC",
    "742": "Uterine and adnexa procedures for non-malignancy with CC/MCC",
    "743": "Uterine and adnexa procedures for non-malignancy without CC/MCC",
    "744": "D&C, conization, laparoscopy and tubal interruption with CC/MCC",
    "745": "D&C, conization, laparoscopy and tubal interruption without CC/MCC",
    "746": "Vagina, cervix and vulva procedures with CC/MCC",
    "747": "Vagina, cervix and vulva procedures without CC/MCC",
    "748": "Female reproductive system reconstructive procedures",
    "749": "Other female reproductive system O.R. procedures with CC/MCC",
    "750": "Other female reproductive system O.R. procedures without CC/MCC",
    "754": "Malignancy, female reproductive system with MCC",
    "755": "Malignancy, female reproductive system with CC",
    "756": "Malignancy, female reproductive system without CC/MCC",
    "757": "Infections, female reproductive system with MCC",
    "758": "Infections, female reproductive system with CC",
    "759": "Infections, female reproductive system without CC/MCC",
    "760": "Menstrual and other female reproductive system disorders with CC/MCC",
    "761": "Menstrual and other female reproductive system disorders without CC/MCC",
    "768": "Vaginal delivery with O.R. proc except steril &/or D&C",
    "769": "Postpartum and post abortion diagnoses with O.R. procedure",
    "770": "Abortion with D&C, aspiration curettage or hysterotomy",
    "776": "Postpartum and post abortion diagnoses without O.R. procedure",
    "779": "Abortion without D&C",
    "783": "Cesarean section with sterilization with MCC",
    "784": "Cesarean section with sterilization with CC",
    "785": "Cesarean section with sterilization without CC/MCC",
    "786": "Cesarean section without sterilization with MCC",
    "787": "Cesarean section without sterilization with CC",
    "788": "Cesarean section without sterilization without CC/MCC",
    "789": "Neonates, died or transferred to another acute care facility",
    "790": "Extreme immaturity or respiratory distress syndrome, neonate",
    "791": "Prematurity with major problems",
    "792": "Prematurity without major problems",
    "793": "Full term neonate with major problems",
    "794": "Neonate with other significant problems",
    "795": "Normal newborn",
    "796": "Vaginal delivery with sterilization/D&C with MCC",
    "797": "Vaginal delivery with sterilization/D&C with CC",
    "798": "Vaginal delivery with sterilization/D&C without CC/MCC",
    "799": "Splenectomy with MCC",
    "800": "Splenectomy with CC",
    "801": "Splenectomy without CC/MCC",
    "802": "Other O.R. procedures of the blood and blood forming organs with MCC",
    "803": "Other O.R. procedures of the blood and blood forming organs with CC",
    "804": "Other O.R. procedures of the blood and blood forming organs without CC/MCC",
    "805": "Vaginal delivery without sterilization/D&C with MCC",
    "806": "Vaginal delivery without sterilization/D&C with CC",
    "807": "Vaginal delivery without sterilization/D&C without CC/MCC",
    "808": "Major hematological and immunological diagnoses except sickle cell crisis and coagulation disorders with MCC",
    "809": "Major hematological and immunological diagnoses except sickle cell crisis and coagulation disorders with CC",
    "810": "Major hematological and immunological diagnoses except sickle cell crisis and coagulation disorders without CC/MCC",
    "811": "Red blood cell disorders with MCC",
    "812": "Red blood cell disorders without MCC",
    "813": "Coagulation disorders",
    "814": "Reticuloendothelial and immunity disorders with MCC",
    "815": "Reticuloendothelial and immunity disorders with CC",
    "816": "Reticuloendothelial and immunity disorders without CC/MCC",
    "817": "Other antepartum diagnoses with O.R. procedure with MCC",
    "818": "Other antepartum diagnoses with O.R. procedure with CC",
    "819": "Other antepartum diagnoses with O.R. procedure without CC/MCC",
    "820": "Lymphoma and leukemia with major O.R. procedure with MCC",
    "821": "Lymphoma and leukemia with major O.R. procedure with CC",
    "822": "Lymphoma and leukemia with major O.R. procedure without CC/MCC",
    "823": "Lymphoma and non-acute leukemia with other procedure with MCC",
    "824": "Lymphoma and non-acute leukemia with other procedure with CC",
    "825": "Lymphoma and non-acute leukemia with other procedure without CC/MCC",
    "826": "Myeloproliferative disorders or poorly differentiated neoplasms with major O.R. procedure with MCC",
    "827": "Myeloproliferative disorders or poorly differentiated neoplasms with major O.R. procedure with CC",
    "828": "Myeloproliferative disorders or poorly differentiated neoplasms with major O.R. procedure without CC/MCC",
    "829": "Myeloproliferative disorders or poorly differentiated neoplasms with other procedure with CC/MCC",
    "830": "Myeloproliferative disorders or poorly differentiated neoplasms with other procedure without CC/MCC",
    "831": "Other antepartum diagnoses without O.R. procedure with MCC",
    "832": "Other antepartum diagnoses without O.R. procedure with CC",
    "833": "Other antepartum diagnoses without O.R. procedure without CC/MCC",
    "834": "Acute leukemia without major O.R. procedure with MCC",
    "835": "Acute leukemia without major O.R. procedure with CC",
    "836": "Acute leukemia without major O.R. procedure without CC/MCC",
    "837": "Chemotherapy with acute leukemia as SDX or with high dose chemotherapy agent with MCC",
    "838": "Chemotherapy with acute leukemia as SDX with CC or high dose chemotherapy agent",
    "839": "Chemotherapy with acute leukemia as SDX without CC/MCC",
    "840": "Lymphoma and non-acute leukemia with MCC",
    "841": "Lymphoma and non-acute leukemia with CC",
    "842": "Lymphoma and non-acute leukemia without CC/MCC",
    "843": "Other myeloproliferative disorders or poorly differentiated neoplastic diagnoses with MCC",
    "844": "Other myeloproliferative disorders or poorly differentiated neoplastic diagnoses with CC",
    "845": "Other myeloproliferative disorders or poorly differentiated neoplastic diagnoses without CC/MCC",
    "846": "Chemotherapy without acute leukemia as secondary diagnosis with MCC",
    "847": "Chemotherapy without acute leukemia as secondary diagnosis with CC",
    "848": "Chemotherapy without acute leukemia as secondary diagnosis without CC/MCC",
    "849": "Radiotherapy",
    "853": "Infectious and parasitic diseases with O.R. procedure with MCC",
    "854": "Infectious and parasitic diseases with O.R. procedure with CC",
    "855": "Infectious and parasitic diseases with O.R. procedure without CC/MCC",
    "856": "Postoperative or post-traumatic infections with O.R. procedure with MCC",
    "857": "Postoperative or post-traumatic infections with O.R. procedure with CC",
    "858": "Postoperative or post-traumatic infections with O.R. procedure without CC/MCC",
    "862": "Postoperative and post-traumatic infections with MCC",
    "863": "Postoperative and post-traumatic infections without MCC",
    "864": "Fever and inflammatory conditions",
    "865": "Viral illness with MCC",
    "866": "Viral illness without MCC",
    "867": "Other infectious and parasitic diseases diagnoses with MCC",
    "868": "Other infectious and parasitic diseases diagnoses with CC",
    "869": "Other infectious and parasitic diseases diagnoses without CC/MCC",
    "870": "Septicemia or severe sepsis with MV >96 hours",
    "871": "Septicemia or severe sepsis without MV >96 hours with MCC",
    "872": "Septicemia or severe sepsis without MV >96 hours without MCC",
    "876": "O.R. procedure with principal diagnoses of mental illness",
    "880": "Acute adjustment reaction and psychosocial dysfunction",
    "881": "Depressive neuroses",
    "882": "Neuroses except depressive",
    "883": "Disorders of personality and impulse control",
    "884": "Organic disturbances and intellectual disability",
    "885": "Psychoses",
    "886": "Behavioral and developmental disorders",
    "887": "Other mental disorder diagnoses",
    "894": "Alcohol, drug abuse or dependence, left AMA",
    "895": "Alcohol, drug abuse or dependence with rehabilitation therapy",
    "896": "Alcohol, drug abuse or dependence without rehabilitation therapy with MCC",
    "897": "Alcohol, drug abuse or dependence without rehabilitation therapy without MCC",
    "901": "Wound debridements for injuries with MCC",
    "902": "Wound debridements for injuries with CC",
    "903": "Wound debridements for injuries without CC/MCC",
    "904": "Skin grafts for injuries with CC/MCC",
    "905": "Skin grafts for injuries without CC/MCC",
    "906": "Hand procedures for injuries",
    "907": "Other O.R. procedures for injuries with MCC",
    "908": "Other O.R. procedures for injuries with CC",
    "909": "Other O.R. procedures for injuries without CC/MCC",
    "913": "Traumatic injury with MCC",
    "914": "Traumatic injury without MCC",
    "915": "Allergic reactions with MCC",
    "916": "Allergic reactions without MCC",
    "917": "Poisoning and toxic effects of drugs with MCC",
    "918": "Poisoning and toxic effects of drugs without MCC",
    "919": "Complications of treatment with MCC",
    "920": "Complications of treatment with CC",
    "921": "Complications of treatment without CC/MCC",
    "922": "Other injury, poisoning and toxic effect diagnoses with MCC",
    "923": "Other injury, poisoning and toxic effect diagnoses without MCC",
    "927": "Extensive burns or full thickness burns with MV >96 hours with skin graft",
    "928": "Full thickness burn with skin graft or inhalation injury with CC/MCC",
    "929": "Full thickness burn with skin graft or inhalation injury without CC/MCC",
    "933": "Extensive burns or full thickness burns with MV >96 hours without skin graft",
    "934": "Full thickness burn without skin graft or inhalation injury",
    "935": "Non-extensive burns",
    "939": "O.R. procedures with diagnoses of other contact with health services with MCC",
    "940": "O.R. procedures with diagnoses of other contact with health services with CC",
    "941": "O.R. procedures with diagnoses of other contact with health services without CC/MCC",
    "945": "Rehabilitation with CC/MCC",
    "946": "Rehabilitation without CC/MCC",
    "947": "Signs and symptoms with MCC",
    "948": "Signs and symptoms without MCC",
    "949": "Aftercare with CC/MCC",
    "950": "Aftercare without CC/MCC",
    "951": "Other factors influencing health status",
    "955": "Craniotomy for multiple significant trauma",
    "956": "Limb reattachment, hip and femur procedures for multiple significant trauma",
    "957": "Other O.R. procedures for multiple significant trauma with MCC",
    "958": "Other O.R. procedures for multiple significant trauma with CC",
    "959": "Other O.R. procedures for multiple significant trauma without CC/MCC",
    "963": "Other multiple significant trauma with MCC",
    "964": "Other multiple significant trauma with CC",
    "965": "Other multiple significant trauma without CC/MCC",
    "969": "HIV with extensive O.R. procedure with MCC",
    "970": "HIV with extensive O.R. procedure without MCC",
    "974": "HIV with major related condition with MCC",
    "975": "HIV with major related condition with CC",
    "976": "HIV with major related condition without CC/MCC",
    "977": "HIV with or without other related condition",
    "981": "Extensive O.R. procedure unrelated to principal diagnosis with MCC",
    "982": "Extensive O.R. procedure unrelated to principal diagnosis with CC",
    "983": "Extensive O.R. procedure unrelated to principal diagnosis without CC/MCC",
    "987": "Non-extensive O.R. procedure unrelated to principal diagnosis with MCC",
    "988": "Non-extensive O.R. procedure unrelated to principal diagnosis with CC",
    "989": "Non-extensive O.R. procedure unrelated to principal diagnosis without CC/MCC",
    "998": "Principal diagnosis invalid as discharge diagnosis"
}

export default x