const x = [
    { "drg": "001", "desc": "Heart transplant or implant of heart assist system with MCC" },
    { "drg": "002", "desc": "Heart transplant or implant of heart assist system without MCC" },
    { "drg": "003", "desc": "ECMO or tracheostomy with MV >96 hours or PDX except face, mouth and neck with major O.R. procedure" },
    { "drg": "004", "desc": "Tracheostomy with MV >96 hours or PDX except face, mouth and neck without major O.R. procedure" },
    { "drg": "005", "desc": "Liver transplant with MCC or intestinal transplant" },
    { "drg": "006", "desc": "Liver transplant without MCC" },
    { "drg": "007", "desc": "Lung transplant" },
    { "drg": "008", "desc": "Simultaneous pancreas and kidney transplant" },
    { "drg": "010", "desc": "Pancreas transplant" },
    { "drg": "011", "desc": "Tracheostomy for face, mouth & neck diagnoses or laryngectomy with MCC" },
    { "drg": "012", "desc": "Tracheostomy for face, mouth & neck diagnoses or laryngectomy with CC" },
    { "drg": "013", "desc": "Tracheostomy for face, mouth & neck diagnoses or laryngectomy without CC/MCC" },
    { "drg": "014", "desc": "Allogeneic bone marrow transplant" },
    { "drg": "016", "desc": "Autologous bone marrow transplant with CC/MCC or T-cell immunotherapy" },
    { "drg": "017", "desc": "Autologous bone marrow transplant without CC/MCC" },
    { "drg": "020", "desc": "Intracranial vascular procedures with PDX hemorrhage with MCC" },
    { "drg": "021", "desc": "Intracranial vascular procedures with PDX hemorrhage with CC" },
    { "drg": "022", "desc": "Intracranial vascular procedures with PDX hemorrhage without CC/MCC" },
    { "drg": "023", "desc": "Craniotomy with major device implant or acute complex CNS PDX with MCC or chemotherapy implant or epilepsy with neurostimulator" },
    { "drg": "024", "desc": "Craniotomy with major device implant or acute complex CNS PDX without MCC" },
    { "drg": "025", "desc": "Craniotomy and endovascular intracranial procedures with MCC" },
    { "drg": "026", "desc": "Craniotomy and endovascular intracranial procedures with CC" },
    { "drg": "027", "desc": "Craniotomy and endovascular intracranial procedures without CC/MCC" },
    { "drg": "028", "desc": "Spinal procedures with MCC" },
    { "drg": "029", "desc": "Spinal procedures with CC or spinal neurostimulators" },
    { "drg": "030", "desc": "Spinal procedures without CC/MCC" },
    { "drg": "031", "desc": "Ventricular shunt procedures with MCC" },
    { "drg": "032", "desc": "Ventricular shunt procedures with CC" },
    { "drg": "033", "desc": "Ventricular shunt procedures without CC/MCC" },
    { "drg": "034", "desc": "Carotid artery stent procedure with MCC" },
    { "drg": "035", "desc": "Carotid artery stent procedure with CC" },
    { "drg": "036", "desc": "Carotid artery stent procedure without CC/MCC" },
    { "drg": "037", "desc": "Extracranial procedures with MCC" },
    { "drg": "038", "desc": "Extracranial procedures with CC" },
    { "drg": "039", "desc": "Extracranial procedures without CC/MCC" },
    { "drg": "040", "desc": "Peripheral, cranial nerve and other nervous system procedures with MCC" },
    { "drg": "041", "desc": "Peripheral, cranial nerve and other nervous system procedures with CC or peripheral neurostimulator" },
    { "drg": "042", "desc": "Peripheral, cranial nerve and other nervous system procedures without CC/MCC" },
    { "drg": "052", "desc": "Spinal disorders and injuries with CC/MCC" },
    { "drg": "053", "desc": "Spinal disorders and injuries without CC/MCC" },
    { "drg": "054", "desc": "Nervous system neoplasms with MCC" },
    { "drg": "055", "desc": "Nervous system neoplasms without MCC" },
    { "drg": "056", "desc": "Degenerative nervous system disorders with MCC" },
    { "drg": "057", "desc": "Degenerative nervous system disorders without MCC" },
    { "drg": "058", "desc": "Multiple sclerosis and cerebellar ataxia with MCC" },
    { "drg": "059", "desc": "Multiple sclerosis and cerebellar ataxia with CC" },
    { "drg": "060", "desc": "Multiple sclerosis and cerebellar ataxia without CC/MCC" },
    { "drg": "061", "desc": "Ischemic stroke, precerebral occlusion or transient ischemia with thrombolytic agent with MCC" },
    { "drg": "062", "desc": "Ischemic stroke, precerebral occlusion or transient ischemia with thrombolytic agent with CC" },
    { "drg": "063", "desc": "Ischemic stroke, precerebral occlusion or transient ischemia with thrombolytic agent without CC/MCC" },
    { "drg": "064", "desc": "Intracranial hemorrhage or cerebral infarction with MCC" },
    { "drg": "065", "desc": "Intracranial hemorrhage or cerebral infarction with CC or tPA in 24 hours" },
    { "drg": "066", "desc": "Intracranial hemorrhage or cerebral infarction without CC/MCC" },
    { "drg": "067", "desc": "Nonspecific CVA and precerebral occlusion without infarction with MCC" },
    { "drg": "068", "desc": "Nonspecific CVA and precerebral occlusion without infarction without MCC" },
    { "drg": "069", "desc": "Transient ischemia without thrombolytic" },
    { "drg": "070", "desc": "Nonspecific cerebrovascular disorders with MCC" },
    { "drg": "071", "desc": "Nonspecific cerebrovascular disorders with CC" },
    { "drg": "072", "desc": "Nonspecific cerebrovascular disorders without CC/MCC" },
    { "drg": "073", "desc": "Cranial and peripheral nerve disorders with MCC" },
    { "drg": "074", "desc": "Cranial and peripheral nerve disorders without MCC" },
    { "drg": "075", "desc": "Viral meningitis with CC/MCC" },
    { "drg": "076", "desc": "Viral meningitis without CC/MCC" },
    { "drg": "077", "desc": "Hypertensive encephalopathy with MCC" },
    { "drg": "078", "desc": "Hypertensive encephalopathy with CC" },
    { "drg": "079", "desc": "Hypertensive encephalopathy without CC/MCC" },
    { "drg": "080", "desc": "Nontraumatic stupor and coma with MCC" },
    { "drg": "081", "desc": "Nontraumatic stupor and coma without MCC" },
    { "drg": "082", "desc": "Traumatic stupor and coma, coma >1 hour with MCC" },
    { "drg": "083", "desc": "Traumatic stupor and coma, coma >1 hour with CC" },
    { "drg": "084", "desc": "Traumatic stupor and coma, coma >1 hour without CC/MCC" },
    { "drg": "085", "desc": "Traumatic stupor and coma, coma <1 hour with MCC" },
    { "drg": "086", "desc": "Traumatic stupor and coma, coma <1 hour with CC" },
    { "drg": "087", "desc": "Traumatic stupor and coma, coma <1 hour without CC/MCC" },
    { "drg": "088", "desc": "Concussion with MCC" },
    { "drg": "089", "desc": "Concussion with CC" },
    { "drg": "090", "desc": "Concussion without CC/MCC" },
    { "drg": "091", "desc": "Other disorders of nervous system with MCC" },
    { "drg": "092", "desc": "Other disorders of nervous system with CC" },
    { "drg": "093", "desc": "Other disorders of nervous system without CC/MCC" },
    { "drg": "094", "desc": "Bacterial and tuberculous infections of nervous system with MCC" },
    { "drg": "095", "desc": "Bacterial and tuberculous infections of nervous system with CC" },
    { "drg": "096", "desc": "Bacterial and tuberculous infections of nervous system without CC/MCC" },
    { "drg": "097", "desc": "Non-bacterial infection of nervous system except viral meningitis with MCC" },
    { "drg": "098", "desc": "Non-bacterial infection of nervous system except viral meningitis with CC" },
    { "drg": "099", "desc": "Non-bacterial infection of nervous system except viral meningitis without CC/MCC" },
    { "drg": "100", "desc": "Seizures with MCC" },
    { "drg": "101", "desc": "Seizures without MCC" },
    { "drg": "102", "desc": "Headaches with MCC" },
    { "drg": "103", "desc": "Headaches without MCC" },
    { "drg": "113", "desc": "Orbital procedures with CC/MCC" },
    { "drg": "114", "desc": "Orbital procedures without CC/MCC" },
    { "drg": "115", "desc": "Extraocular procedures except orbit" },
    { "drg": "116", "desc": "Intraocular procedures with CC/MCC" },
    { "drg": "117", "desc": "Intraocular procedures without CC/MCC" },
    { "drg": "121", "desc": "Acute major eye infections with CC/MCC" },
    { "drg": "122", "desc": "Acute major eye infections without CC/MCC" },
    { "drg": "123", "desc": "Neurological eye disorders" },
    { "drg": "124", "desc": "Other disorders of the eye with MCC" },
    { "drg": "125", "desc": "Other disorders of the eye without MCC" },
    { "drg": "129", "desc": "Major head and neck procedures with CC/MCC or major device" },
    { "drg": "130", "desc": "Major head and neck procedures without CC/MCC" },
    { "drg": "131", "desc": "Cranial and facial procedures with CC/MCC" },
    { "drg": "132", "desc": "Cranial and facial procedures without CC/MCC" },
    { "drg": "133", "desc": "Other ear, nose, mouth and throat O.R. procedures with CC/MCC" },
    { "drg": "134", "desc": "Other ear, nose, mouth and throat O.R. procedures without CC/MCC" },
    { "drg": "135", "desc": "Sinus and mastoid procedures with CC/MCC" },
    { "drg": "136", "desc": "Sinus and mastoid procedures without CC/MCC" },
    { "drg": "137", "desc": "Mouth procedures with CC/MCC" },
    { "drg": "138", "desc": "Mouth procedures without CC/MCC" },
    { "drg": "139", "desc": "Salivary gland procedures" },
    { "drg": "146", "desc": "Ear, nose, mouth and throat malignancy with MCC" },
    { "drg": "147", "desc": "Ear, nose, mouth and throat malignancy with CC" },
    { "drg": "148", "desc": "Ear, nose, mouth and throat malignancy without CC/MCC" },
    { "drg": "149", "desc": "Dysequilibrium" },
    { "drg": "150", "desc": "Epistaxis with MCC" },
    { "drg": "151", "desc": "Epistaxis without MCC" },
    { "drg": "152", "desc": "Otitis media and URI with MCC" },
    { "drg": "153", "desc": "Otitis media and URI without MCC" },
    { "drg": "154", "desc": "Other ear, nose, mouth and throat diagnoses with MCC" },
    { "drg": "155", "desc": "Other ear, nose, mouth and throat diagnoses with CC" },
    { "drg": "156", "desc": "Other ear, nose, mouth and throat diagnoses without CC/MCC" },
    { "drg": "157", "desc": "Dental and oral diseases with MCC" },
    { "drg": "158", "desc": "Dental and oral diseases with CC" },
    { "drg": "159", "desc": "Dental and oral diseases without CC/MCC" },
    { "drg": "163", "desc": "Major chest procedures with MCC" },
    { "drg": "164", "desc": "Major chest procedures with CC" },
    { "drg": "165", "desc": "Major chest procedures without CC/MCC" },
    { "drg": "166", "desc": "Other respiratory system O.R. procedures with MCC" },
    { "drg": "167", "desc": "Other respiratory system O.R. procedures with CC" },
    { "drg": "168", "desc": "Other respiratory system O.R. procedures without CC/MCC" },
    { "drg": "175", "desc": "Pulmonary embolism with MCC or acute cor pulmonale" },
    { "drg": "176", "desc": "Pulmonary embolism without MCC" },
    { "drg": "177", "desc": "Respiratory infections and inflammations with MCC" },
    { "drg": "178", "desc": "Respiratory infections and inflammations with CC" },
    { "drg": "179", "desc": "Respiratory infections and inflammations without CC/MCC" },
    { "drg": "180", "desc": "Respiratory neoplasms with MCC" },
    { "drg": "181", "desc": "Respiratory neoplasms with CC" },
    { "drg": "182", "desc": "Respiratory neoplasms without CC/MCC" },
    { "drg": "183", "desc": "Major chest trauma with MCC" },
    { "drg": "184", "desc": "Major chest trauma with CC" },
    { "drg": "185", "desc": "Major chest trauma without CC/MCC" },
    { "drg": "186", "desc": "Pleural effusion with MCC" },
    { "drg": "187", "desc": "Pleural effusion with CC" },
    { "drg": "188", "desc": "Pleural effusion without CC/MCC" },
    { "drg": "189", "desc": "Pulmonary edema and respiratory failure" },
    { "drg": "190", "desc": "Chronic obstructive pulmonary disease with MCC" },
    { "drg": "191", "desc": "Chronic obstructive pulmonary disease with CC" },
    { "drg": "192", "desc": "Chronic obstructive pulmonary disease without CC/MCC" },
    { "drg": "193", "desc": "Simple pneumonia and pleurisy with MCC" },
    { "drg": "194", "desc": "Simple pneumonia and pleurisy with CC" },
    { "drg": "195", "desc": "Simple pneumonia and pleurisy without CC/MCC" },
    { "drg": "196", "desc": "Interstitial lung disease with MCC" },
    { "drg": "197", "desc": "Interstitial lung disease with CC" },
    { "drg": "198", "desc": "Interstitial lung disease without CC/MCC" },
    { "drg": "199", "desc": "Pneumothorax with MCC" },
    { "drg": "200", "desc": "Pneumothorax with CC" },
    { "drg": "201", "desc": "Pneumothorax without CC/MCC" },
    { "drg": "202", "desc": "Bronchitis and asthma with CC/MCC" },
    { "drg": "203", "desc": "Bronchitis and asthma without CC/MCC" },
    { "drg": "204", "desc": "Respiratory signs and symptoms" },
    { "drg": "205", "desc": "Other respiratory system diagnoses with MCC" },
    { "drg": "206", "desc": "Other respiratory system diagnoses without MCC" },
    { "drg": "207", "desc": "Respiratory system diagnosis with ventilator support >96 hours" },
    { "drg": "208", "desc": "Respiratory system diagnosis with ventilator support <=96 hours" },
    { "drg": "215", "desc": "Other heart assist system implant" },
    { "drg": "216", "desc": "Cardiac valve and other major cardiothoracic procedures with cardiac catheterization with MCC" },
    { "drg": "217", "desc": "Cardiac valve and other major cardiothoracic procedures with cardiac catheterization with CC" },
    { "drg": "218", "desc": "Cardiac valve and other major cardiothoracic procedures with cardiac catheterization without CC/MCC" },
    { "drg": "219", "desc": "Cardiac valve and other major cardiothoracic procedures without cardiac catheterization with MCC" },
    { "drg": "220", "desc": "Cardiac valve and other major cardiothoracic procedures without cardiac catheterization with CC" },
    { "drg": "221", "desc": "Cardiac valve and other major cardiothoracic procedures without cardiac catheterization without CC/MCC" },
    { "drg": "222", "desc": "Cardiac defibrillator implant with cardiac catheterization with AMI/HF/shock with MCC" },
    { "drg": "223", "desc": "Cardiac defibrillator implant with cardiac catheterization with AMI/HF/shock without MCC" },
    { "drg": "224", "desc": "Cardiac defibrillator implant with cardiac catheterization without AMI/HF/shock with MCC" },
    { "drg": "225", "desc": "Cardiac defibrillator implant with cardiac catheterization without AMI/HF/shock without MCC" },
    { "drg": "226", "desc": "Cardiac defibrillator implant without cardiac catheterization with MCC" },
    { "drg": "227", "desc": "Cardiac defibrillator implant without cardiac catheterization without MCC" },
    { "drg": "228", "desc": "Other cardiothoracic procedures with MCC" },
    { "drg": "229", "desc": "Other cardiothoracic procedures without MCC" },
    { "drg": "231", "desc": "Coronary bypass with PTCA with MCC" },
    { "drg": "232", "desc": "Coronary bypass with PTCA without MCC" },
    { "drg": "233", "desc": "Coronary bypass with cardiac catheterization with MCC" },
    { "drg": "234", "desc": "Coronary bypass with cardiac catheterization without MCC" },
    { "drg": "235", "desc": "Coronary bypass without cardiac catheterization with MCC" },
    { "drg": "236", "desc": "Coronary bypass without cardiac catheterization without MCC" },
    { "drg": "239", "desc": "Amputation for circulatory system disorders except upper limb and toe with MCC" },
    { "drg": "240", "desc": "Amputation for circulatory system disorders except upper limb and toe with CC" },
    { "drg": "241", "desc": "Amputation for circulatory system disorders except upper limb and toe without CC/MCC" },
    { "drg": "242", "desc": "Permanent cardiac pacemaker implant with MCC" },
    { "drg": "243", "desc": "Permanent cardiac pacemaker implant with CC" },
    { "drg": "244", "desc": "Permanent cardiac pacemaker implant without CC/MCC" },
    { "drg": "245", "desc": "AICD generator procedures" },
    { "drg": "246", "desc": "Percutaneous cardiovascular procedures with drug-eluting stent with MCC or 4+ arteries or stents" },
    { "drg": "247", "desc": "Percutaneous cardiovascular procedures with drug-eluting stent without MCC" },
    { "drg": "248", "desc": "Percutaneous cardiovascular procedures with non-drug-eluting stent with MCC or 4+ arteries or stents" },
    { "drg": "249", "desc": "Percutaneous cardiovascular procedures with non-drug-eluting stent without MCC" },
    { "drg": "250", "desc": "Percutaneous cardiovascular procedures without coronary artery stent with MCC" },
    { "drg": "251", "desc": "Percutaneous cardiovascular procedures without coronary artery stent without MCC" },
    { "drg": "252", "desc": "Other vascular procedures with MCC" },
    { "drg": "253", "desc": "Other vascular procedures with CC" },
    { "drg": "254", "desc": "Other vascular procedures without CC/MCC" },
    { "drg": "255", "desc": "Upper limb and toe amputation for circulatory system disorders with MCC" },
    { "drg": "256", "desc": "Upper limb and toe amputation for circulatory system disorders with CC" },
    { "drg": "257", "desc": "Upper limb and toe amputation for circulatory system disorders without CC/MCC" },
    { "drg": "258", "desc": "Cardiac pacemaker device replacement with MCC" },
    { "drg": "259", "desc": "Cardiac pacemaker device replacement without MCC" },
    { "drg": "260", "desc": "Cardiac pacemaker revision except device replacement with MCC" },
    { "drg": "261", "desc": "Cardiac pacemaker revision except device replacement with CC" },
    { "drg": "262", "desc": "Cardiac pacemaker revision except device replacement without CC/MCC" },
    { "drg": "263", "desc": "Vein ligation and stripping" },
    { "drg": "264", "desc": "Other circulatory system O.R. procedures" },
    { "drg": "265", "desc": "AICD lead procedures" },
    { "drg": "266", "desc": "Endovascular cardiac valve replacement and supplement procedures with MCC" },
    { "drg": "267", "desc": "Endovascular cardiac valve replacement and supplement procedures without MCC" },
    { "drg": "268", "desc": "Aortic and heart assist procedures except pulsation balloon with MCC" },
    { "drg": "269", "desc": "Aortic and heart assist procedures except pulsation balloon without MCC" },
    { "drg": "270", "desc": "Other major cardiovascular procedures with MCC" },
    { "drg": "271", "desc": "Other major cardiovascular procedures with CC" },
    { "drg": "272", "desc": "Other major cardiovascular procedures without CC/MCC" },
    { "drg": "273", "desc": "Percutaneous intracardiac procedures with MCC" },
    { "drg": "274", "desc": "Percutaneous intracardiac procedures without MCC" },
    { "drg": "280", "desc": "Acute myocardial infarction, discharged alive with MCC" },
    { "drg": "281", "desc": "Acute myocardial infarction, discharged alive with CC" },
    { "drg": "282", "desc": "Acute myocardial infarction, discharged alive without CC/MCC" },
    { "drg": "283", "desc": "Acute myocardial infarction, expired with MCC" },
    { "drg": "284", "desc": "Acute myocardial infarction, expired with CC" },
    { "drg": "285", "desc": "Acute myocardial infarction, expired without CC/MCC" },
    { "drg": "286", "desc": "Circulatory disorders except AMI, with cardiac cateterization with MCC" },
    { "drg": "287", "desc": "Circulatory disorders except AMI, with cardiac cateterization without MCC" },
    { "drg": "288", "desc": "Acute and subacute endocarditis with MCC" },
    { "drg": "289", "desc": "Acute and subacute endocarditis with CC" },
    { "drg": "290", "desc": "Acute and subacute endocarditis without CC/MCC" },
    { "drg": "291", "desc": "Heart failure and shock with MCC" },
    { "drg": "292", "desc": "Heart failure and shock with CC" },
    { "drg": "293", "desc": "Heart failure and shock without CC/MCC" },
    { "drg": "294", "desc": "Deep vein thrombophlebitis with CC/MCC" },
    { "drg": "295", "desc": "Deep vein thrombophlebitis without CC/MCC" },
    { "drg": "296", "desc": "Cardiac arrest, unexplained with MCC" },
    { "drg": "297", "desc": "Cardiac arrest, unexplained with CC" },
    { "drg": "298", "desc": "Cardiac arrest, unexplained without CC/MCC" },
    { "drg": "299", "desc": "Peripheral vascular disorders with MCC" },
    { "drg": "300", "desc": "Peripheral vascular disorders with CC" },
    { "drg": "301", "desc": "Peripheral vascular disorders without CC/MCC" },
    { "drg": "302", "desc": "Atherosclerosis with MCC" },
    { "drg": "303", "desc": "Atherosclerosis without MCC" },
    { "drg": "304", "desc": "Hypertension with MCC" },
    { "drg": "305", "desc": "Hypertension without MCC" },
    { "drg": "306", "desc": "Cardiac congenital and valvular disorders with MCC" },
    { "drg": "307", "desc": "Cardiac congenital and valvular disorders without MCC" },
    { "drg": "308", "desc": "Cardiac arrhythmia and conduction disorders with MCC" },
    { "drg": "309", "desc": "Cardiac arrhythmia and conduction disorders with CC" },
    { "drg": "310", "desc": "Cardiac arrhythmia and conduction disorders without CC/MCC" },
    { "drg": "311", "desc": "Angina pectoris" },
    { "drg": "312", "desc": "Syncope and collapse" },
    { "drg": "313", "desc": "Chest pain" },
    { "drg": "314", "desc": "Other circulatory system diagnoses with MCC" },
    { "drg": "315", "desc": "Other circulatory system diagnoses with CC" },
    { "drg": "316", "desc": "Other circulatory system diagnoses without CC/MCC" },
    { "drg": "319", "desc": "Other endovascular cardiac valve procedures with MCC" },
    { "drg": "320", "desc": "Other endovascular cardiac valve procedures without MCC" },
    { "drg": "326", "desc": "Stomach, esophageal and duodenal procedures with MCC" },
    { "drg": "327", "desc": "Stomach, esophageal and duodenal procedures with CC" },
    { "drg": "328", "desc": "Stomach, esophageal and duodenal procedures without CC/MCC" },
    { "drg": "329", "desc": "Major small and large bowel procedures with MCC" },
    { "drg": "330", "desc": "Major small and large bowel procedures with CC" },
    { "drg": "331", "desc": "Major small and large bowel procedures without CC/MCC" },
    { "drg": "332", "desc": "Rectal resection with MCC" },
    { "drg": "333", "desc": "Rectal resection with CC" },
    { "drg": "334", "desc": "Rectal resection without CC/MCC" },
    { "drg": "335", "desc": "Peritoneal adhesiolysis with MCC" },
    { "drg": "336", "desc": "Peritoneal adhesiolysis with CC" },
    { "drg": "337", "desc": "Peritoneal adhesiolysis without CC/MCC" },
    { "drg": "338", "desc": "Appendectomy with complicated principal diagnosis with MCC" },
    { "drg": "339", "desc": "Appendectomy with complicated principal diagnosis with CC" },
    { "drg": "340", "desc": "Appendectomy with complicated principal diagnosis without CC/MCC" },
    { "drg": "341", "desc": "Appendectomy without complicated principal diagnosis with MCC" },
    { "drg": "342", "desc": "Appendectomy without complicated principal diagnosis with CC" },
    { "drg": "343", "desc": "Appendectomy without complicated principal diagnosis without CC/MCC" },
    { "drg": "344", "desc": "Minor small and large bowel procedures with MCC" },
    { "drg": "345", "desc": "Minor small and large bowel procedures with CC" },
    { "drg": "346", "desc": "Minor small and large bowel procedures without CC/MCC" },
    { "drg": "347", "desc": "Anal and stomal procedures with MCC" },
    { "drg": "348", "desc": "Anal and stomal procedures with CC" },
    { "drg": "349", "desc": "Anal and stomal procedures without CC/MCC" },
    { "drg": "350", "desc": "Inguinal and femoral hernia procedures with MCC" },
    { "drg": "351", "desc": "Inguinal and femoral hernia procedures with CC" },
    { "drg": "352", "desc": "Inguinal and femoral hernia procedures without CC/MCC" },
    { "drg": "353", "desc": "Hernia procedures except inguinal and femoral with MCC" },
    { "drg": "354", "desc": "Hernia procedures except inguinal and femoral with CC" },
    { "drg": "355", "desc": "Hernia procedures except inguinal and femoral without CC/MCC" },
    { "drg": "356", "desc": "Other digestive system O.R. procedures with MCC" },
    { "drg": "357", "desc": "Other digestive system O.R. procedures with CC" },
    { "drg": "358", "desc": "Other digestive system O.R. procedures without CC/MCC" },
    { "drg": "368", "desc": "Major esophageal disorders with MCC" },
    { "drg": "369", "desc": "Major esophageal disorders with CC" },
    { "drg": "370", "desc": "Major esophageal disorders without CC/MCC" },
    { "drg": "371", "desc": "Major gastrointestinal disorders and peritoneal infections with MCC" },
    { "drg": "372", "desc": "Major gastrointestinal disorders and peritoneal infections with CC" },
    { "drg": "373", "desc": "Major gastrointestinal disorders and peritoneal infections without CC/MCC" },
    { "drg": "374", "desc": "Digestive malignancy with MCC" },
    { "drg": "375", "desc": "Digestive malignancy with CC" },
    { "drg": "376", "desc": "Digestive malignancy without CC/MCC" },
    { "drg": "377", "desc": "G.I. hemorrhage with MCC" },
    { "drg": "378", "desc": "G.I. hemorrhage with CC" },
    { "drg": "379", "desc": "G.I. hemorrhage without CC/MCC" },
    { "drg": "380", "desc": "Complicated peptic ulcer with MCC" },
    { "drg": "381", "desc": "Complicated peptic ulcer with CC" },
    { "drg": "382", "desc": "Complicated peptic ulcer without CC/MCC" },
    { "drg": "383", "desc": "Uncomplicated peptic ulcer with MCC" },
    { "drg": "384", "desc": "Uncomplicated peptic ulcer without MCC" },
    { "drg": "385", "desc": "Inflammatory bowel disease with MCC" },
    { "drg": "386", "desc": "Inflammatory bowel disease with CC" },
    { "drg": "387", "desc": "Inflammatory bowel disease without CC/MCC" },
    { "drg": "388", "desc": "G.I. obstruction with MCC" },
    { "drg": "389", "desc": "G.I. obstruction with CC" },
    { "drg": "390", "desc": "G.I. obstruction without CC/MCC" },
    { "drg": "391", "desc": "Esophagitis, gastroenteritis and miscellaneous digestive disorders with MCC" },
    { "drg": "392", "desc": "Esophagitis, gastroenteritis and miscellaneous digestive disorders without MCC" },
    { "drg": "393", "desc": "Other digestive system diagnoses with MCC" },
    { "drg": "394", "desc": "Other digestive system diagnoses with CC" },
    { "drg": "395", "desc": "Other digestive system diagnoses without CC/MCC" },
    { "drg": "405", "desc": "Pancreas, liver and shunt procedures with MCC" },
    { "drg": "406", "desc": "Pancreas, liver and shunt procedures with CC" },
    { "drg": "407", "desc": "Pancreas, liver and shunt procedures without CC/MCC" },
    { "drg": "408", "desc": "Biliary tract procedure except only cholecystectomy with or without C.D.E. with MCC" },
    { "drg": "409", "desc": "Biliary tract procedure except only cholecystectomy with or without C.D.E. with CC" },
    { "drg": "410", "desc": "Biliary tract procedure except only cholecystectomy with or without C.D.E. without CC/MCC" },
    { "drg": "411", "desc": "Cholecystectomy with C.D.E. with MCC" },
    { "drg": "412", "desc": "Cholecystectomy with C.D.E. with CC" },
    { "drg": "413", "desc": "Cholecystectomy with C.D.E. without CC/MCC" },
    { "drg": "414", "desc": "Cholecystectomy except by laparoscope without C.D.E. with MCC" },
    { "drg": "415", "desc": "Cholecystectomy except by laparoscope without C.D.E. with CC" },
    { "drg": "416", "desc": "Cholecystectomy except by laparoscope without C.D.E. without CC/MCC" },
    { "drg": "417", "desc": "Laparoscopic cholecystectomy without C.D.E. with MCC" },
    { "drg": "418", "desc": "Laparoscopic cholecystectomy without C.D.E. with CC" },
    { "drg": "419", "desc": "Laparoscopic cholecystectomy without C.D.E. without CC/MCC" },
    { "drg": "420", "desc": "Hepatobiliary diagnostic procedures with MCC" },
    { "drg": "421", "desc": "Hepatobiliary diagnostic procedures with CC" },
    { "drg": "422", "desc": "Hepatobiliary diagnostic procedures without CC/MCC" },
    { "drg": "423", "desc": "Other hepatobiliary or pancreas O.R. procedures with MCC" },
    { "drg": "424", "desc": "Other hepatobiliary or pancreas O.R. procedures with CC" },
    { "drg": "425", "desc": "Other hepatobiliary or pancreas O.R. procedures without CC/MCC" },
    { "drg": "432", "desc": "Cirrhosis and alcoholic hepatitis with MCC" },
    { "drg": "433", "desc": "Cirrhosis and alcoholic hepatitis with CC" },
    { "drg": "434", "desc": "Cirrhosis and alcoholic hepatitis without CC/MCC" },
    { "drg": "435", "desc": "Malignancy of hepatobiliary system or pancreas with MCC" },
    { "drg": "436", "desc": "Malignancy of hepatobiliary system or pancreas with CC" },
    { "drg": "437", "desc": "Malignancy of hepatobiliary system or pancreas without CC/MCC" },
    { "drg": "438", "desc": "Disorders of pancreas except malignancy with MCC" },
    { "drg": "439", "desc": "Disorders of pancreas except malignancy with CC" },
    { "drg": "440", "desc": "Disorders of pancreas except malignancy without CC/MCC" },
    { "drg": "441", "desc": "Disorders of liver except malignancy, cirrhosis or alcoholic hepatitis with MCC" },
    { "drg": "442", "desc": "Disorders of liver except malignancy, cirrhosis or alcoholic hepatitis with CC" },
    { "drg": "443", "desc": "Disorders of liver except malignancy, cirrhosis or alcoholic hepatitis without CC/MCC" },
    { "drg": "444", "desc": "Disorders of the biliary tract with MCC" },
    { "drg": "445", "desc": "Disorders of the biliary tract with CC" },
    { "drg": "446", "desc": "Disorders of the biliary tract without CC/MCC" },
    { "drg": "453", "desc": "Combined anterior/posterior spinal fusion with MCC" },
    { "drg": "454", "desc": "Combined anterior/posterior spinal fusion with CC" },
    { "drg": "455", "desc": "Combined anterior/posterior spinal fusion without CC/MCC" },
    { "drg": "456", "desc": "Spinal fusion except cervical with spinal curvature or malignancy or infection or extensive fusions with MCC" },
    { "drg": "457", "desc": "Spinal fusion except cervical with spinal curvature or malignancy or infection or extensive fusions with CC" },
    { "drg": "458", "desc": "Spinal fusion except cervical with spinal curvature or malignancy or infection or extensive fusions without CC/MCC" },
    { "drg": "459", "desc": "Spinal fusion except cervical with MCC" },
    { "drg": "460", "desc": "Spinal fusion except cervical without MCC" },
    { "drg": "461", "desc": "Bilateral or multiple major joint procedures of lower extremity with MCC" },
    { "drg": "462", "desc": "Bilateral or multiple major joint procedures of lower extremity without MCC" },
    { "drg": "463", "desc": "Wound debridement and skin graft except hand for musculoskeletal system and connective tissue disorders with MCC" },
    { "drg": "464", "desc": "Wound debridement and skin graft except hand for musculoskeletal system and connective tissue disorders with CC" },
    { "drg": "465", "desc": "Wound debridement and skin graft except hand for musculoskeletal system and connective tissue disorders without CC/MCC" },
    { "drg": "466", "desc": "Revision of hip or knee replacement with MCC" },
    { "drg": "467", "desc": "Revision of hip or knee replacement with CC" },
    { "drg": "468", "desc": "Revision of hip or knee replacement without CC/MCC" },
    { "drg": "469", "desc": "Major hip and knee joint replacement or reattachment of lower extremity with MCC or total ankle replacement" },
    { "drg": "470", "desc": "Major hip and knee joint replacement or reattachment of lower extremity without MCC" },
    { "drg": "471", "desc": "Cervical spinal fusion with MCC" },
    { "drg": "472", "desc": "Cervical spinal fusion with CC" },
    { "drg": "473", "desc": "Cervical spinal fusion without CC/MCC" },
    { "drg": "474", "desc": "Amputation for musculoskeletal system and connective tissue disorders with MCC" },
    { "drg": "475", "desc": "Amputation for musculoskeletal system and connective tissue disorders with CC" },
    { "drg": "476", "desc": "Amputation for musculoskeletal system and connective tissue disorders without CC/MCC" },
    { "drg": "477", "desc": "Biopsies of musculoskeletal system and connective tissue with MCC" },
    { "drg": "478", "desc": "Biopsies of musculoskeletal system and connective tissue with CC" },
    { "drg": "479", "desc": "Biopsies of musculoskeletal system and connective tissue without CC/MCC" },
    { "drg": "480", "desc": "Hip and femur procedures except major joint with MCC" },
    { "drg": "481", "desc": "Hip and femur procedures except major joint with CC" },
    { "drg": "482", "desc": "Hip and femur procedures except major joint without CC/MCC" },
    { "drg": "483", "desc": "Major joint/limb reattachment procedure of upper extremities" },
    { "drg": "485", "desc": "Knee procedures with PDX of infection with MCC" },
    { "drg": "486", "desc": "Knee procedures with PDX of infection with CC" },
    { "drg": "487", "desc": "Knee procedures with PDX of infection without CC/MCC" },
    { "drg": "488", "desc": "Knee procedures without PDX of infection with CC/MCC" },
    { "drg": "489", "desc": "Knee procedures without PDX of infection without CC/MCC" },
    { "drg": "492", "desc": "Lower extremity and humerus procedures except hip, foot and femur with MCC" },
    { "drg": "493", "desc": "Lower extremity and humerus procedures except hip, foot and femur with CC" },
    { "drg": "494", "desc": "Lower extremity and humerus procedures except hip, foot and femur without CC/MCC" },
    { "drg": "495", "desc": "Local excision and removal of internal fixation devices except hip and femur with MCC" },
    { "drg": "496", "desc": "Local excision and removal of internal fixation devices except hip and femur with CC" },
    { "drg": "497", "desc": "Local excision and removal internal fixation devices except hip and femur without CC/MCC" },
    { "drg": "498", "desc": "Local excision and removal internal fixation devices of hip and femur with CC/MCC" },
    { "drg": "499", "desc": "Local excision and removal internal fixation devices of hip and femur without CC/MCC" },
    { "drg": "500", "desc": "Soft tissue procedures with MCC" },
    { "drg": "501", "desc": "Soft tissue procedures with CC" },
    { "drg": "502", "desc": "Soft tissue procedures without CC/MCC" },
    { "drg": "503", "desc": "Foot procedures with MCC" },
    { "drg": "504", "desc": "Foot procedures with CC" },
    { "drg": "505", "desc": "Foot procedures without CC/MCC" },
    { "drg": "506", "desc": "Major thumb or joint procedures" },
    { "drg": "507", "desc": "Major shoulder or elbow joint procedures with CC/MCC" },
    { "drg": "508", "desc": "Major shoulder or elbow joint procedures without CC/MCC" },
    { "drg": "509", "desc": "Arthroscopy" },
    { "drg": "510", "desc": "Shoulder, elbow or forearm procedures, except major joint procedures with MCC" },
    { "drg": "511", "desc": "Shoulder, elbow or forearm procedures, except major joint procedures with CC" },
    { "drg": "512", "desc": "Shoulder, elbow or forearm procedures, except major joint procedures without CC/MCC" },
    { "drg": "513", "desc": "Hand or wrist procedures, except major thumb or joint procedures with CC/MCC" },
    { "drg": "514", "desc": "Hand or wrist procedures, except major thumb or joint procedures without CC/MCC" },
    { "drg": "515", "desc": "Other musculoskeletal system and connective tissue O.R. procedures with MCC" },
    { "drg": "516", "desc": "Other musculoskeletal system and connective tissue O.R. procedures with CC" },
    { "drg": "517", "desc": "Other musculoskeletal system and connective tissue O.R. procedures without CC/MCC" },
    { "drg": "518", "desc": "Back and neck procedures except spinal fusion with MCC or disc device or neurostimulator" },
    { "drg": "519", "desc": "Back and neck procedures except spinal fusion with CC" },
    { "drg": "520", "desc": "Back and neck procedures except spinal fusion without CC/MCC" },
    { "drg": "533", "desc": "Fractures of femur with MCC" },
    { "drg": "534", "desc": "Fractures of femur without MCC" },
    { "drg": "535", "desc": "Fractures of hip and pelvis with MCC" },
    { "drg": "536", "desc": "Fractures of hip and pelvis without MCC" },
    { "drg": "537", "desc": "Sprains, strains, and dislocations of hip, pelvis and thigh with CC/MCC" },
    { "drg": "538", "desc": "Sprains, strains, and dislocations of hip, pelvis and thigh without CC/MCC" },
    { "drg": "539", "desc": "Osteomyelitis with MCC" },
    { "drg": "540", "desc": "Osteomyelitis with CC" },
    { "drg": "541", "desc": "Osteomyelitis without CC/MCC" },
    { "drg": "542", "desc": "Pathological fractures and musculoskeletal and connective tissue malignancy with MCC" },
    { "drg": "543", "desc": "Pathological fractures and musculoskeletal and connective tissue malignancy with CC" },
    { "drg": "544", "desc": "Pathological fractures and musculoskeletal and connective tissue malignancy without CC/MCC" },
    { "drg": "545", "desc": "Connective tissue disorders with MCC" },
    { "drg": "546", "desc": "Connective tissue disorders with CC" },
    { "drg": "547", "desc": "Connective tissue disorders without CC/MCC" },
    { "drg": "548", "desc": "Septic arthritis with MCC" },
    { "drg": "549", "desc": "Septic arthritis with CC" },
    { "drg": "550", "desc": "Septic arthritis without CC/MCC" },
    { "drg": "551", "desc": "Medical back problems with MCC" },
    { "drg": "552", "desc": "Medical back problems without MCC" },
    { "drg": "553", "desc": "Bone diseases and arthropathies with MCC" },
    { "drg": "554", "desc": "Bone diseases and arthropathies without MCC" },
    { "drg": "555", "desc": "Signs and symptoms of musculoskeletal system and connective tissue with MCC" },
    { "drg": "556", "desc": "Signs and symptoms of musculoskeletal system and connective tissue without MCC" },
    { "drg": "557", "desc": "Tendonitis, myositis and bursitis with MCC" },
    { "drg": "558", "desc": "Tendonitis, myositis and bursitis without MCC" },
    { "drg": "559", "desc": "Aftercare, musculoskeletal system and connective tissue with MCC" },
    { "drg": "560", "desc": "Aftercare, musculoskeletal system and connective tissue with CC" },
    { "drg": "561", "desc": "Aftercare, musculoskeletal system and connective tissue without CC/MCC" },
    { "drg": "562", "desc": "Fracture, sprain, strain and dislocation except femur, hip, pelvis and thigh with MCC" },
    { "drg": "563", "desc": "Fracture, sprain, strain and dislocation except femur, hip, pelvis and thigh without MCC" },
    { "drg": "564", "desc": "Other musculoskeletal system and connective tissue diagnoses with MCC" },
    { "drg": "565", "desc": "Other musculoskeletal system and connective tissue diagnoses with CC" },
    { "drg": "566", "desc": "Other musculoskeletal system and connective tissue diagnoses without CC/MCC" },
    { "drg": "570", "desc": "Skin debridement with MCC" },
    { "drg": "571", "desc": "Skin debridement with CC" },
    { "drg": "572", "desc": "Skin debridement without CC/MCC" },
    { "drg": "573", "desc": "Skin graft for skin ulcer or cellulitis with MCC" },
    { "drg": "574", "desc": "Skin graft for skin ulcer or cellulitis with CC" },
    { "drg": "575", "desc": "Skin graft for skin ulcer or cellulitis without CC/MCC" },
    { "drg": "576", "desc": "Skin graft except for skin ulcer or cellulitis with MCC" },
    { "drg": "577", "desc": "Skin graft except for skin ulcer or cellulitis with CC" },
    { "drg": "578", "desc": "Skin graft except for skin ulcer or cellulitis without CC/MCC" },
    { "drg": "579", "desc": "Other skin, subcutaneous tissue and breast procedures with MCC" },
    { "drg": "580", "desc": "Other skin, subcutaneous tissue and breast procedures with CC" },
    { "drg": "581", "desc": "Other skin, subcutaneous tissue and breast procedures without CC/MCC" },
    { "drg": "582", "desc": "Mastectomy for malignancy with CC/MCC" },
    { "drg": "583", "desc": "Mastectomy for malignancy without CC/MCC" },
    { "drg": "584", "desc": "Breast biopsy, local excision and other breast procedures with CC/MCC" },
    { "drg": "585", "desc": "Breast biopsy, local excision and other breast procedures without CC/MCC" },
    { "drg": "592", "desc": "Skin ulcers with MCC" },
    { "drg": "593", "desc": "Skin ulcers with CC" },
    { "drg": "594", "desc": "Skin ulcers without CC/MCC" },
    { "drg": "595", "desc": "Major skin disorders with MCC" },
    { "drg": "596", "desc": "Major skin disorders without MCC" },
    { "drg": "597", "desc": "Malignant breast disorders with MCC" },
    { "drg": "598", "desc": "Malignant breast disorders with CC" },
    { "drg": "599", "desc": "Malignant breast disorders without CC/MCC" },
    { "drg": "600", "desc": "Non-malignant breast disorders with CC/MCC" },
    { "drg": "601", "desc": "Non-malignant breast disorders without CC/MCC" },
    { "drg": "602", "desc": "Cellulitis with MCC" },
    { "drg": "603", "desc": "Cellulitis without MCC" },
    { "drg": "604", "desc": "Trauma to the skin, subcutaneous tissue and breast with MCC" },
    { "drg": "605", "desc": "Trauma to the skin, subcutaneous tissue and breast without MCC" },
    { "drg": "606", "desc": "Minor skin disorders with MCC" },
    { "drg": "607", "desc": "Minor skin disorders without MCC" },
    { "drg": "614", "desc": "Adrenal and pituitary procedures with CC/MCC" },
    { "drg": "615", "desc": "Adrenal and pituitary procedures without CC/MCC" },
    { "drg": "616", "desc": "Amputation of lower limb for endocrine, nutritional and metabolic disorders with MCC" },
    { "drg": "617", "desc": "Amputation of lower limb for endocrine, nutritional and metabolic disorders with CC" },
    { "drg": "618", "desc": "Amputation of lower limb for endocrine, nutritional and metabolic disorders without CC/MCC" },
    { "drg": "619", "desc": "O.R. procedures for obesity with MCC" },
    { "drg": "620", "desc": "O.R. procedures for obesity with CC" },
    { "drg": "621", "desc": "O.R. procedures for obesity without CC/MCC" },
    { "drg": "622", "desc": "Skin grafts and wound debridement for endocrine, nutritional and metabolic disorders with MCC" },
    { "drg": "623", "desc": "Skin grafts and wound debridement for endocrine, nutritional and metabolic disorders with CC" },
    { "drg": "624", "desc": "Skin grafts and wound debridement for endocrine, nutritional and metabolic disorders without CC/MCC" },
    { "drg": "625", "desc": "Thyroid, parathyroid and thyroglossal procedures with MCC" },
    { "drg": "626", "desc": "Thyroid, parathyroid and thyroglossal procedures with CC" },
    { "drg": "627", "desc": "Thyroid, parathyroid and thyroglossal procedures without CC/MCC" },
    { "drg": "628", "desc": "Other endocrine, nutritional and metabolic O.R. procedures with MCC" },
    { "drg": "629", "desc": "Other endocrine, nutritional and metabolic O.R. procedures with CC" },
    { "drg": "630", "desc": "Other endocrine, nutritional and metabolic O.R. procedures without CC/MCC" },
    { "drg": "637", "desc": "Diabetes with MCC" },
    { "drg": "638", "desc": "Diabetes with CC" },
    { "drg": "639", "desc": "Diabetes without CC/MCC" },
    { "drg": "640", "desc": "Miscellaneous disorders of nutrition, metabolism, fluids and electrolytes with MCC" },
    { "drg": "641", "desc": "Miscellaneous disorders of nutrition, metabolism, fluids and electrolytes without MCC" },
    { "drg": "642", "desc": "Inborn and other disorders of metabolism" },
    { "drg": "643", "desc": "Endocrine disorders with MCC" },
    { "drg": "644", "desc": "Endocrine disorders with CC" },
    { "drg": "645", "desc": "Endocrine disorders without CC/MCC" },
    { "drg": "652", "desc": "Kidney transplant" },
    { "drg": "653", "desc": "Major bladder procedures with MCC" },
    { "drg": "654", "desc": "Major bladder procedures with CC" },
    { "drg": "655", "desc": "Major bladder procedures without CC/MCC" },
    { "drg": "656", "desc": "Kidney and ureter procedures for neoplasm with MCC" },
    { "drg": "657", "desc": "Kidney and ureter procedures for neoplasm with CC" },
    { "drg": "658", "desc": "Kidney and ureter procedures for neoplasm without CC/MCC" },
    { "drg": "659", "desc": "Kidney and ureter procedures for non-neoplasm with MCC" },
    { "drg": "660", "desc": "Kidney and ureter procedures for non-neoplasm with CC" },
    { "drg": "661", "desc": "Kidney and ureter procedures for non-neoplasm without CC/MCC" },
    { "drg": "662", "desc": "Minor bladder procedures with MCC" },
    { "drg": "663", "desc": "Minor bladder procedures with CC" },
    { "drg": "664", "desc": "Minor bladder procedures without CC/MCC" },
    { "drg": "665", "desc": "Prostatectomy with MCC" },
    { "drg": "666", "desc": "Prostatectomy with CC" },
    { "drg": "667", "desc": "Prostatectomy without CC/MCC" },
    { "drg": "668", "desc": "Transurethral procedures with MCC" },
    { "drg": "669", "desc": "Transurethral procedures with CC" },
    { "drg": "670", "desc": "Transurethral procedures without CC/MCC" },
    { "drg": "671", "desc": "Urethral procedures with CC/MCC" },
    { "drg": "672", "desc": "Urethral procedures without CC/MCC" },
    { "drg": "673", "desc": "Other kidney and urinary tract procedures with MCC" },
    { "drg": "674", "desc": "Other kidney and urinary tract procedures with CC" },
    { "drg": "675", "desc": "Other kidney and urinary tract procedures without CC/MCC" },
    { "drg": "682", "desc": "Renal failure with MCC" },
    { "drg": "683", "desc": "Renal failure with CC" },
    { "drg": "684", "desc": "Renal failure without CC/MCC" },
    { "drg": "686", "desc": "Kidney and urinary tract neoplasms with MCC" },
    { "drg": "687", "desc": "Kidney and urinary tract neoplasms with CC" },
    { "drg": "688", "desc": "Kidney and urinary tract neoplasms without CC/MCC" },
    { "drg": "689", "desc": "Kidney and urinary tract infections with MCC" },
    { "drg": "690", "desc": "Kidney and urinary tract infections without MCC" },
    { "drg": "693", "desc": "Urinary stones with MCC" },
    { "drg": "694", "desc": "Urinary stones without MCC" },
    { "drg": "695", "desc": "Kidney and urinary tract signs and symptoms with MCC" },
    { "drg": "696", "desc": "Kidney and urinary tract signs and symptoms without MCC" },
    { "drg": "697", "desc": "Urethral stricture" },
    { "drg": "698", "desc": "Other kidney and urinary tract diagnoses with MCC" },
    { "drg": "699", "desc": "Other kidney and urinary tract diagnoses with CC" },
    { "drg": "700", "desc": "Other kidney and urinary tract diagnoses without CC/MCC" },
    { "drg": "707", "desc": "Major male pelvic procedures with CC/MCC" },
    { "drg": "708", "desc": "Major male pelvic procedures without CC/MCC" },
    { "drg": "709", "desc": "Penis procedures with CC/MCC" },
    { "drg": "710", "desc": "Penis procedures without CC/MCC" },
    { "drg": "711", "desc": "Testes procedures with CC/MCC" },
    { "drg": "712", "desc": "Testes procedures without CC/MCC" },
    { "drg": "713", "desc": "Transurethral prostatectomy with CC/MCC" },
    { "drg": "714", "desc": "Transurethral prostatectomy without CC/MCC" },
    { "drg": "715", "desc": "Other male reproductive system O.R. procedures for malignancy with CC/MCC" },
    { "drg": "716", "desc": "Other male reproductive system O.R. procedures for malignancy without CC/MCC" },
    { "drg": "717", "desc": "Other male reproductive system O.R. procedures except malignancy with CC/MCC" },
    { "drg": "718", "desc": "Other male reproductive system O.R. proc except malignancy without CC/MCC" },
    { "drg": "722", "desc": "Malignancy, male reproductive system with MCC" },
    { "drg": "723", "desc": "Malignancy, male reproductive system with CC" },
    { "drg": "724", "desc": "Malignancy, male reproductive system without CC/MCC" },
    { "drg": "725", "desc": "Benign prostatic hypertrophy with MCC" },
    { "drg": "726", "desc": "Benign prostatic hypertrophy without MCC" },
    { "drg": "727", "desc": "Inflammation of the male reproductive system with MCC" },
    { "drg": "728", "desc": "Inflammation of the male reproductive system without MCC" },
    { "drg": "729", "desc": "Other male reproductive system diagnoses with CC/MCC" },
    { "drg": "730", "desc": "Other male reproductive system diagnoses without CC/MCC" },
    { "drg": "734", "desc": "Pelvic evisceration, radical hysterectomy and radical vulvectomy with CC/MCC" },
    { "drg": "735", "desc": "Pelvic evisceration, radical hysterectomy and radical vulvectomy without CC/MCC" },
    { "drg": "736", "desc": "Uterine and adnexa procedures for ovarian or adnexal malignancy with MCC" },
    { "drg": "737", "desc": "Uterine and adnexa procedures for ovarian or adnexal malignancy with CC" },
    { "drg": "738", "desc": "Uterine and adnexa procedures for ovarian or adnexal malignancy without CC/MCC" },
    { "drg": "739", "desc": "Uterine, adnexa procedures for non-ovarian and non-adnexal malignancy with MCC" },
    { "drg": "740", "desc": "Uterine, adnexa procedures for non-ovarian and non-adnexal malignancy with CC" },
    { "drg": "741", "desc": "Uterine, adnexa procedures for non-ovarian and non-adnexal malignancy without CC/MCC" },
    { "drg": "742", "desc": "Uterine and adnexa procedures for non-malignancy with CC/MCC" },
    { "drg": "743", "desc": "Uterine and adnexa procedures for non-malignancy without CC/MCC" },
    { "drg": "744", "desc": "D&C, conization, laparoscopy and tubal interruption with CC/MCC" },
    { "drg": "745", "desc": "D&C, conization, laparoscopy and tubal interruption without CC/MCC" },
    { "drg": "746", "desc": "Vagina, cervix and vulva procedures with CC/MCC" },
    { "drg": "747", "desc": "Vagina, cervix and vulva procedures without CC/MCC" },
    { "drg": "748", "desc": "Female reproductive system reconstructive procedures" },
    { "drg": "749", "desc": "Other female reproductive system O.R. procedures with CC/MCC" },
    { "drg": "750", "desc": "Other female reproductive system O.R. procedures without CC/MCC" },
    { "drg": "754", "desc": "Malignancy, female reproductive system with MCC" },
    { "drg": "755", "desc": "Malignancy, female reproductive system with CC" },
    { "drg": "756", "desc": "Malignancy, female reproductive system without CC/MCC" },
    { "drg": "757", "desc": "Infections, female reproductive system with MCC" },
    { "drg": "758", "desc": "Infections, female reproductive system with CC" },
    { "drg": "759", "desc": "Infections, female reproductive system without CC/MCC" },
    { "drg": "760", "desc": "Menstrual and other female reproductive system disorders with CC/MCC" },
    { "drg": "761", "desc": "Menstrual and other female reproductive system disorders without CC/MCC" },
    { "drg": "768", "desc": "Vaginal delivery with O.R. proc except steril &/or D&C" },
    { "drg": "769", "desc": "Postpartum and post abortion diagnoses with O.R. procedure" },
    { "drg": "770", "desc": "Abortion with D&C, aspiration curettage or hysterotomy" },
    { "drg": "776", "desc": "Postpartum and post abortion diagnoses without O.R. procedure" },
    { "drg": "779", "desc": "Abortion without D&C" },
    { "drg": "783", "desc": "Cesarean section with sterilization with MCC" },
    { "drg": "784", "desc": "Cesarean section with sterilization with CC" },
    { "drg": "785", "desc": "Cesarean section with sterilization without CC/MCC" },
    { "drg": "786", "desc": "Cesarean section without sterilization with MCC" },
    { "drg": "787", "desc": "Cesarean section without sterilization with CC" },
    { "drg": "788", "desc": "Cesarean section without sterilization without CC/MCC" },
    { "drg": "789", "desc": "Neonates, died or transferred to another acute care facility" },
    { "drg": "790", "desc": "Extreme immaturity or respiratory distress syndrome, neonate" },
    { "drg": "791", "desc": "Prematurity with major problems" },
    { "drg": "792", "desc": "Prematurity without major problems" },
    { "drg": "793", "desc": "Full term neonate with major problems" },
    { "drg": "794", "desc": "Neonate with other significant problems" },
    { "drg": "795", "desc": "Normal newborn" },
    { "drg": "796", "desc": "Vaginal delivery with sterilization/D&C with MCC" },
    { "drg": "797", "desc": "Vaginal delivery with sterilization/D&C with CC" },
    { "drg": "798", "desc": "Vaginal delivery with sterilization/D&C without CC/MCC" },
    { "drg": "799", "desc": "Splenectomy with MCC" },
    { "drg": "800", "desc": "Splenectomy with CC" },
    { "drg": "801", "desc": "Splenectomy without CC/MCC" },
    { "drg": "802", "desc": "Other O.R. procedures of the blood and blood forming organs with MCC" },
    { "drg": "803", "desc": "Other O.R. procedures of the blood and blood forming organs with CC" },
    { "drg": "804", "desc": "Other O.R. procedures of the blood and blood forming organs without CC/MCC" },
    { "drg": "805", "desc": "Vaginal delivery without sterilization/D&C with MCC" },
    { "drg": "806", "desc": "Vaginal delivery without sterilization/D&C with CC" },
    { "drg": "807", "desc": "Vaginal delivery without sterilization/D&C without CC/MCC" },
    { "drg": "808", "desc": "Major hematological and immunological diagnoses except sickle cell crisis and coagulation disorders with MCC" },
    { "drg": "809", "desc": "Major hematological and immunological diagnoses except sickle cell crisis and coagulation disorders with CC" },
    { "drg": "810", "desc": "Major hematological and immunological diagnoses except sickle cell crisis and coagulation disorders without CC/MCC" },
    { "drg": "811", "desc": "Red blood cell disorders with MCC" },
    { "drg": "812", "desc": "Red blood cell disorders without MCC" },
    { "drg": "813", "desc": "Coagulation disorders" },
    { "drg": "814", "desc": "Reticuloendothelial and immunity disorders with MCC" },
    { "drg": "815", "desc": "Reticuloendothelial and immunity disorders with CC" },
    { "drg": "816", "desc": "Reticuloendothelial and immunity disorders without CC/MCC" },
    { "drg": "817", "desc": "Other antepartum diagnoses with O.R. procedure with MCC" },
    { "drg": "818", "desc": "Other antepartum diagnoses with O.R. procedure with CC" },
    { "drg": "819", "desc": "Other antepartum diagnoses with O.R. procedure without CC/MCC" },
    { "drg": "820", "desc": "Lymphoma and leukemia with major O.R. procedure with MCC" },
    { "drg": "821", "desc": "Lymphoma and leukemia with major O.R. procedure with CC" },
    { "drg": "822", "desc": "Lymphoma and leukemia with major O.R. procedure without CC/MCC" },
    { "drg": "823", "desc": "Lymphoma and non-acute leukemia with other procedure with MCC" },
    { "drg": "824", "desc": "Lymphoma and non-acute leukemia with other procedure with CC" },
    { "drg": "825", "desc": "Lymphoma and non-acute leukemia with other procedure without CC/MCC" },
    { "drg": "826", "desc": "Myeloproliferative disorders or poorly differentiated neoplasms with major O.R. procedure with MCC" },
    { "drg": "827", "desc": "Myeloproliferative disorders or poorly differentiated neoplasms with major O.R. procedure with CC" },
    { "drg": "828", "desc": "Myeloproliferative disorders or poorly differentiated neoplasms with major O.R. procedure without CC/MCC" },
    { "drg": "829", "desc": "Myeloproliferative disorders or poorly differentiated neoplasms with other procedure with CC/MCC" },
    { "drg": "830", "desc": "Myeloproliferative disorders or poorly differentiated neoplasms with other procedure without CC/MCC" },
    { "drg": "831", "desc": "Other antepartum diagnoses without O.R. procedure with MCC" },
    { "drg": "832", "desc": "Other antepartum diagnoses without O.R. procedure with CC" },
    { "drg": "833", "desc": "Other antepartum diagnoses without O.R. procedure without CC/MCC" },
    { "drg": "834", "desc": "Acute leukemia without major O.R. procedure with MCC" },
    { "drg": "835", "desc": "Acute leukemia without major O.R. procedure with CC" },
    { "drg": "836", "desc": "Acute leukemia without major O.R. procedure without CC/MCC" },
    { "drg": "837", "desc": "Chemotherapy with acute leukemia as SDX or with high dose chemotherapy agent with MCC" },
    { "drg": "838", "desc": "Chemotherapy with acute leukemia as SDX with CC or high dose chemotherapy agent" },
    { "drg": "839", "desc": "Chemotherapy with acute leukemia as SDX without CC/MCC" },
    { "drg": "840", "desc": "Lymphoma and non-acute leukemia with MCC" },
    { "drg": "841", "desc": "Lymphoma and non-acute leukemia with CC" },
    { "drg": "842", "desc": "Lymphoma and non-acute leukemia without CC/MCC" },
    { "drg": "843", "desc": "Other myeloproliferative disorders or poorly differentiated neoplastic diagnoses with MCC" },
    { "drg": "844", "desc": "Other myeloproliferative disorders or poorly differentiated neoplastic diagnoses with CC" },
    { "drg": "845", "desc": "Other myeloproliferative disorders or poorly differentiated neoplastic diagnoses without CC/MCC" },
    { "drg": "846", "desc": "Chemotherapy without acute leukemia as secondary diagnosis with MCC" },
    { "drg": "847", "desc": "Chemotherapy without acute leukemia as secondary diagnosis with CC" },
    { "drg": "848", "desc": "Chemotherapy without acute leukemia as secondary diagnosis without CC/MCC" },
    { "drg": "849", "desc": "Radiotherapy" },
    { "drg": "853", "desc": "Infectious and parasitic diseases with O.R. procedure with MCC" },
    { "drg": "854", "desc": "Infectious and parasitic diseases with O.R. procedure with CC" },
    { "drg": "855", "desc": "Infectious and parasitic diseases with O.R. procedure without CC/MCC" },
    { "drg": "856", "desc": "Postoperative or post-traumatic infections with O.R. procedure with MCC" },
    { "drg": "857", "desc": "Postoperative or post-traumatic infections with O.R. procedure with CC" },
    { "drg": "858", "desc": "Postoperative or post-traumatic infections with O.R. procedure without CC/MCC" },
    { "drg": "862", "desc": "Postoperative and post-traumatic infections with MCC" },
    { "drg": "863", "desc": "Postoperative and post-traumatic infections without MCC" },
    { "drg": "864", "desc": "Fever and inflammatory conditions" },
    { "drg": "865", "desc": "Viral illness with MCC" },
    { "drg": "866", "desc": "Viral illness without MCC" },
    { "drg": "867", "desc": "Other infectious and parasitic diseases diagnoses with MCC" },
    { "drg": "868", "desc": "Other infectious and parasitic diseases diagnoses with CC" },
    { "drg": "869", "desc": "Other infectious and parasitic diseases diagnoses without CC/MCC" },
    { "drg": "870", "desc": "Septicemia or severe sepsis with MV >96 hours" },
    { "drg": "871", "desc": "Septicemia or severe sepsis without MV >96 hours with MCC" },
    { "drg": "872", "desc": "Septicemia or severe sepsis without MV >96 hours without MCC" },
    { "drg": "876", "desc": "O.R. procedure with principal diagnoses of mental illness" },
    { "drg": "880", "desc": "Acute adjustment reaction and psychosocial dysfunction" },
    { "drg": "881", "desc": "Depressive neuroses" },
    { "drg": "882", "desc": "Neuroses except depressive" },
    { "drg": "883", "desc": "Disorders of personality and impulse control" },
    { "drg": "884", "desc": "Organic disturbances and intellectual disability" },
    { "drg": "885", "desc": "Psychoses" },
    { "drg": "886", "desc": "Behavioral and developmental disorders" },
    { "drg": "887", "desc": "Other mental disorder diagnoses" },
    { "drg": "894", "desc": "Alcohol, drug abuse or dependence, left AMA" },
    { "drg": "895", "desc": "Alcohol, drug abuse or dependence with rehabilitation therapy" },
    { "drg": "896", "desc": "Alcohol, drug abuse or dependence without rehabilitation therapy with MCC" },
    { "drg": "897", "desc": "Alcohol, drug abuse or dependence without rehabilitation therapy without MCC" },
    { "drg": "901", "desc": "Wound debridements for injuries with MCC" },
    { "drg": "902", "desc": "Wound debridements for injuries with CC" },
    { "drg": "903", "desc": "Wound debridements for injuries without CC/MCC" },
    { "drg": "904", "desc": "Skin grafts for injuries with CC/MCC" },
    { "drg": "905", "desc": "Skin grafts for injuries without CC/MCC" },
    { "drg": "906", "desc": "Hand procedures for injuries" },
    { "drg": "907", "desc": "Other O.R. procedures for injuries with MCC" },
    { "drg": "908", "desc": "Other O.R. procedures for injuries with CC" },
    { "drg": "909", "desc": "Other O.R. procedures for injuries without CC/MCC" },
    { "drg": "913", "desc": "Traumatic injury with MCC" },
    { "drg": "914", "desc": "Traumatic injury without MCC" },
    { "drg": "915", "desc": "Allergic reactions with MCC" },
    { "drg": "916", "desc": "Allergic reactions without MCC" },
    { "drg": "917", "desc": "Poisoning and toxic effects of drugs with MCC" },
    { "drg": "918", "desc": "Poisoning and toxic effects of drugs without MCC" },
    { "drg": "919", "desc": "Complications of treatment with MCC" },
    { "drg": "920", "desc": "Complications of treatment with CC" },
    { "drg": "921", "desc": "Complications of treatment without CC/MCC" },
    { "drg": "922", "desc": "Other injury, poisoning and toxic effect diagnoses with MCC" },
    { "drg": "923", "desc": "Other injury, poisoning and toxic effect diagnoses without MCC" },
    { "drg": "927", "desc": "Extensive burns or full thickness burns with MV >96 hours with skin graft" },
    { "drg": "928", "desc": "Full thickness burn with skin graft or inhalation injury with CC/MCC" },
    { "drg": "929", "desc": "Full thickness burn with skin graft or inhalation injury without CC/MCC" },
    { "drg": "933", "desc": "Extensive burns or full thickness burns with MV >96 hours without skin graft" },
    { "drg": "934", "desc": "Full thickness burn without skin graft or inhalation injury" },
    { "drg": "935", "desc": "Non-extensive burns" },
    { "drg": "939", "desc": "O.R. procedures with diagnoses of other contact with health services with MCC" },
    { "drg": "940", "desc": "O.R. procedures with diagnoses of other contact with health services with CC" },
    { "drg": "941", "desc": "O.R. procedures with diagnoses of other contact with health services without CC/MCC" },
    { "drg": "945", "desc": "Rehabilitation with CC/MCC" },
    { "drg": "946", "desc": "Rehabilitation without CC/MCC" },
    { "drg": "947", "desc": "Signs and symptoms with MCC" },
    { "drg": "948", "desc": "Signs and symptoms without MCC" },
    { "drg": "949", "desc": "Aftercare with CC/MCC" },
    { "drg": "950", "desc": "Aftercare without CC/MCC" },
    { "drg": "951", "desc": "Other factors influencing health status" },
    { "drg": "955", "desc": "Craniotomy for multiple significant trauma" },
    { "drg": "956", "desc": "Limb reattachment, hip and femur procedures for multiple significant trauma" },
    { "drg": "957", "desc": "Other O.R. procedures for multiple significant trauma with MCC" },
    { "drg": "958", "desc": "Other O.R. procedures for multiple significant trauma with CC" },
    { "drg": "959", "desc": "Other O.R. procedures for multiple significant trauma without CC/MCC" },
    { "drg": "963", "desc": "Other multiple significant trauma with MCC" },
    { "drg": "964", "desc": "Other multiple significant trauma with CC" },
    { "drg": "965", "desc": "Other multiple significant trauma without CC/MCC" },
    { "drg": "969", "desc": "HIV with extensive O.R. procedure with MCC" },
    { "drg": "970", "desc": "HIV with extensive O.R. procedure without MCC" },
    { "drg": "974", "desc": "HIV with major related condition with MCC" },
    { "drg": "975", "desc": "HIV with major related condition with CC" },
    { "drg": "976", "desc": "HIV with major related condition without CC/MCC" },
    { "drg": "977", "desc": "HIV with or without other related condition" },
    { "drg": "981", "desc": "Extensive O.R. procedure unrelated to principal diagnosis with MCC" },
    { "drg": "982", "desc": "Extensive O.R. procedure unrelated to principal diagnosis with CC" },
    { "drg": "983", "desc": "Extensive O.R. procedure unrelated to principal diagnosis without CC/MCC" },
    { "drg": "987", "desc": "Non-extensive O.R. procedure unrelated to principal diagnosis with MCC" },
    { "drg": "988", "desc": "Non-extensive O.R. procedure unrelated to principal diagnosis with CC" },
    { "drg": "989", "desc": "Non-extensive O.R. procedure unrelated to principal diagnosis without CC/MCC" },
    { "drg": "998", "desc": "Principal diagnosis invalid as discharge diagnosis" }
]

export default x